- i18n/src/i18n-messages.json
- public/index.html
- src/components/Captcha.js
- src/components/Email.js
- src/components/Main.js
- src/i18n-messages.js
- src/style/Captcha.scss
- src/style/Email.scss
- src/style/Main.scss
THis fixes the recaptcha page layout
> recaptcha layout

- i18n/l10n/en.json
- i18n/l10n/sv.json
- i18n/src/i18n-messages.json
- public/index.html
- src/components/Captcha.js
- src/components/Email.js
- src/components/Footer.js
- src/components/Main.js
- src/containers/Footer.js
- src/i18n-messages.js
- src/style/Captcha.scss
- src/style/Email.scss
- src/style/Footer.scss
- src/style/Main.scss
Footer with copyright and language selector
> Eperez footer

- src/containers/Email.js
Get the correct TOU form the configuration
> get the correct tou

- i18n/l10n/en.json
- i18n/l10n/sv.json
- i18n/src/i18n-messages.json
- src/i18n-messages.js
- webpack.prod.config.js
- webpack.staging.config.js
correct path for static assets
> correct path for static assets

- src/components/Email.js
> allow html tous

- src/init-config.js
> base path to /register

- package.json
- plugins/eduid_action.mfa/component.js
- plugins/eduid_action.mfa/root-saga.js
- plugins/eduid_action.mfa/store.js
- plugins/eduid_action.mfa/test.js
Using webauthn rather than U2F for mf authentication
> Eperez webauthn

- plugins/eduid_action.mfa/component.js
- plugins/eduid_action.mfa/store.js
Avoid asking the user for webauthn credentials repeatedly
> avoid asking the user for webauthn credentials repeatedly

- i18n/l10n/en.json
- i18n/l10n/sv.json
- i18n/src/i18n-messages.json
- src/i18n-messages.js
Better unsupported browser message
> unsupported browser message

- src/actions/CodeVerified.js
- src/components/CodeVerified.js
- src/containers/CodeVerified.js
- src/reducers/CodeVerified.js
- src/style/CodeVerified.scss
- src/tests/CodeVerified-test.js
finish signup in the dashboard
> finish signup in the dashboard

- plugins/eduid_action.mfa/component.js
- plugins/eduid_action.mfa/root-saga.js
- plugins/eduid_action.mfa/test.js
- src/actions/ActionWrapper.js
- src/sagas/ActionWrapper.js
- src/sagas/cbor.js
- src/tests/ActionWrapper-test.js
Receive actions configuration as cbor
> Eperez webauthn authn

- src/sagas/ActionWrapper.js
> send cbor within json

- src/init-plugin.js
- src/sagas/ActionWrapper.js
show notifications received as get query params
> show notifications received as get query params

- i18n/l10n/en.json
- i18n/l10n/sv.json
- i18n/src/i18n-messages.json
- plugins/eduid_action.mfa/component.js
- src/i18n-messages.js
Try to better inform the user of token authn failures
> try to better inform the user of token authn failures

- plugins/eduid_action.mfa/component.js
- plugins/eduid_action.mfa/style.scss
Fix layout of card with webauthn alternatives
> Fix layout of card with webauthn alternatives

- plugins/eduid_action.mfa/component.js
this line was triggering re-rendering and thus producing a loop
> this line was triggering re-rendering and thus producing a loop

- i18n/l10n/en.json
- i18n/l10n/sv.json
- i18n/src/i18n-messages.json
- plugins/eduid_action.mfa/component.js
- src/i18n-messages.js
advise edge user with u2f key to use other browser
> advise edge user with u2f key to use other browser

- plugins/eduid_action.mfa/component.js
remove wrong message - it is shown (as error) when theres no error
> remove wrong message

- src/components/CodeVerified.js
- src/containers/CodeVerified.js
- src/reducers/CodeVerified.js
- src/tests/CodeVerified-test.js
- src/tests/SignupMain-test.js
Do not do token logins any more
> Eperez session token

- src/components/DashboardMain.js
- src/components/Settings.js
- src/style/base.scss
Summary: 
- creates a new component: Settings.js
- renders a blank dashboard (placeholder header)
- adds a "Settings" button to blank dashboard that triggers render of Settings component
- renders old dashboard in Settings component
> creates and renders settings component

- src/components/DashboardMain.js
- src/components/Settings.js
- src/style/DashboardMain.scss
- src/style/base.scss
Review after [PR 48](https://github.com/SUNET/eduid-front/pull/48)
Summary: 
- adds new content to dashboard
- adds styles to new content
- cleans up Settings component (renders only relevant dashboard content) upon click on "Settings" button
> new dashboard

- src/components/DashboardMain.js
- src/components/Settings.js
- src/components/SettingsButton.js
- src/components/VerifyIdentity.js
- src/style/DashboardMain.scss
- src/style/Notifications.scss
Review after [PR 51](https://github.com/SUNET/eduid-front/pull/51)
Summary: 
- creates new VerifyIdentity component 
- moves dashboard content into VerifyIdentity.js
- makes only VerifyIdentity.js render on "/profile/" and only Settings.js on  "/profile/settings/"
- unifies styling for the two components 
- Hides notifications from the DOM when its empty from text (for now - should show up on top of the Settings component)
> refactor rendering of dashboard and Settings component

- src/components/Settings.js
- src/components/SettingsNav.js
- src/style/DashboardMain.scss
Summary: 
- creates nav on top of Settings that routes to the existing components holding user data
- refactors nav from linking to 6 individual components to only 2 links (personal info & advanced settings) each displaying multiple components 
- splits nav code into a separate SettingsNav component
> adds settings nav

- src/components/DashboardMain.js
- src/components/VerifyIdentity.js
- src/style/DashboardMain.scss
A start at building out the verify identity process from the dashboard:
Summary: 
- makes verify identity button route to '/profile/verify-identity/' on click
- displays Nins component at '/profile/verify-identity/'
**Rough next steps:**
* */profile/verify-identity/*: should  display Step 1 in the process
* **STEP 1** should: ask for Nin and have an `input` that can take it
> I suggest splitting up the current Nin component into: </br>* 1. something that can take/display **only Nin** 
* 2. something that shows just the **three buttons**
* **STEP 2** should: be the confirmation buttons
> establish verify identity process

- src/components/Security.js
correct prop for security modal dialog
> correct prop

- i18n/src/i18n-messages.json
- src/containers/Emails.js
- src/containers/Mobile.js
- src/i18n-messages.js
Fixing the UX for verification codes
> Eperez code modal

- i18n/src/i18n-messages.json
- src/components/ChangePassword.js
- src/containers/ChangePassword.js
- src/containers/Emails.js
- src/containers/Mobile.js
- src/i18n-messages.js
Fixing a problem when changing password and using a custom one
> Eperez no refs

- plugins/eduid_action.mfa/component.js
Prevent the MFA action app from calling credentials.get twice
> Eperez double get

- plugins/eduid_action.mfa/component.js
> Revert "Eperez double get"

- src/sagas/LookupMobileProofing.js
state.form.nins.values has an empty string as value at this point
> state.form.nins.values has an empty string as value at this point

- src/components/ConfirmModal.js
- src/components/Nins.js
- src/containers/Nins.js
- src/tests/Nins-test.js
possible bugfix for a problem verifying nins with letter
> possible bugfix for a problem verifying nins with letter

- i18n/src/i18n-messages.json
- karma.conf.js
- src/components/Captcha.js
- src/components/CodeVerified.js
- src/components/DashboardMain.js
- src/components/Email.js
- src/components/Footer.js
- src/components/HeaderAnon.js
- src/components/LetterProofing.js
- src/components/Security.js
- src/components/SignupMain.js
- src/containers/Email.js
- src/containers/Header.js
- src/i18n-messages.js
- src/tests/AccountCreated-test.js
- src/tests/Captcha-test.js
- src/tests/ChangePassword-test.js
- src/tests/CodeVerified-test.js
- src/tests/DashboardMain-test.js
- src/tests/Email-test.js
- src/tests/EmailInUse-test.js
- src/tests/Footer-test.js
- src/tests/Header-test.js
- src/tests/LetterProofing-test.js
- src/tests/LookupMobileProofing-test.js
- src/tests/ResendCode-test.js
- src/tests/Security-test.js
Background: Existing rendering tests have broken when new design has been applied to the site. These are the first round of fixing the broken tests.
Summary: 
- 14 files have been fixed: AccountCreated, Captcha, ChangePassword, CodeVerified, DashboardMain, Email, EmailInUse, Footer, HeaderAnon/Header, LetterProofing, LookupMobileProofing, Resend Code and Security
- test only check that: 
1. component renders 
2. component renders inputs or buttons (if relevant)
> Fixes rendering tests that have broken during update 

- plugins/eduid_action.tou/component.js
- plugins/eduid_action.tou/style.scss
- src/components/ActionWrapper.js
- src/components/Footer.js
- src/style/Footer.scss
- src/style/Notifications.scss
- src/style/base.scss
**Summary:**
- The updated styling applied (desktop and mobile)
*Some notes for the future:*
- Login Action error page - another static page that needs styling or has it been covered with the styling done in  
- Links in the footer not right colour
- Login button in the top corner of tou - not sure what it should do (bring user back to login?)
> Update styling of terms of use 

- .travis.yml
- src/containers/Eidas.js
concat does not modify in place, it creates a copy
> concat does not modify in place, it creates a copy

- .gitignore
- src/components/Header.js
- src/style/DashboardMain.scss
- src/style/base.scss
**Background**: Header Login button on the Register page redirects to a broken page.
**Summary**: 
- I have added a link to the homepage
> Adds href to header Login button on Register page  

- src/actions/DashboardConfig.js
- src/dashboard-init-app.js
- src/dashboard-root-saga.js
- src/reducers/DashboardConfig.js
Remove configSpa action and related code
> remove SPA configs

- src/actions/ActionWrapper.js
- src/actions/DashboardConfig.js
- src/actions/SignupMain.js
- src/components/ActionWrapper.js
- src/components/Email.js
- src/components/SignupMain.js
- src/containers/ActionWrapper.js
- src/containers/DashboardMain.js
- src/containers/Email.js
- src/containers/HeaderAnon.js
- src/containers/SignupMain.js
- src/reducers/ActionWrapper.js
- src/reducers/DashboardConfig.js
- src/reducers/SignupMain.js
- src/tests/ActionWrapper-test.js
- src/tests/DashboardMain-test.js
- src/tests/SignupMain-test.js
Remove code related to the resizing of windows
> removing resize window functionality - untested

- src/sagas/ChangePassword.js
Separation (in the configuration) of the URL for changing passwords from the URL for other stuff from the security app.
> Eperez change passwd

- i18n/l10n/sv.json
- src/components/DashboardMain.js
Redirect correctly when old redirect links are used in the backend.
> Lundberg redirect old paths

- src/entry-points/plugin-common.js
- src/entry-points/signup.js
Forgot to add the fix to action plugins and signup.
> Added the same dynamic public path for action plugins and signup

- src/login-init-app.js
- src/login-store.js
Redux store for the login app with the common reducers.
init_app function to initialize the login app with the store above.
> initial redux store for the login app

- src/login-init-app.js
- src/login-root-saga.js
- src/login-store.js
Add empty root saga and hook it into redux's middleware
> Eperez login app 2

- src/login-init-app.js
- src/login-root-saga.js
- src/login-store.js
- src/login/LoginMain/LoginMain.js
- src/login/LoginMain/LoginMain.scss
Empty main component for the login app, with:
- splash screen
- notifications container
- routing (hooked into redux middleware)
- fetching context (commented out)
> Eperez login app 3

- src/login-init-app.js
- src/login-root-saga.js
- src/login-store.js
- src/login/LoginMain/LoginMain.js
- src/login/LoginMain/LoginMain.scss
- src/login/LoginMain/LoginMain_container.js
container for the main login component - leaving props untouched for now
> Eperez login app 4

- src/login-init-app.js
- src/login-root-saga.js
- src/login-store.js
- src/login/LoginMain/LoginMain.js
- src/login/LoginMain/LoginMain.scss
- src/login/LoginMain/LoginMain_actions.js
- src/login/LoginMain/LoginMain_container.js
- src/login/LoginMain/LoginMain_reducer.js
> Eperez login app 5

- src/entry-points/login.js
- src/login-init-app.js
- src/login-root-saga.js
- src/login-store.js
- src/login/LoginMain/LoginMain.js
- src/login/LoginMain/LoginMain.scss
- src/login/LoginMain/LoginMain_actions.js
- src/login/LoginMain/LoginMain_container.js
- src/login/LoginMain/LoginMain_reducer.js
- webpack.config.js
Entry point for webpack, it now builds and renders a spinner
> Eperez login app 6

- src/entry-points/login.js
- src/init-config.js
- src/login-init-app.js
- src/login-root-saga.js
- src/login-store.js
- src/login/LoginMain/LoginMain.js
- src/login/LoginMain/LoginMain_actions.js
- src/login/LoginMain/LoginMain_container.js
- src/login/LoginMain/LoginMain_reducer.js
- src/login/LoginMain/LoginMain_sagas.js
- webpack.config.js
> Eperez login app 7

- src/components/Header.js
logo updated to link to the prod dashboard url
> Updates to dynamic href in logo 

- plugins/eduid_action.mfa/index.js
- plugins/eduid_action.mfa/public-path.js
- plugins/eduid_action.tou/index.js
- plugins/eduid_action.tou/public-path.js
- src/components/Email.js
- src/entry-points/login.js
- src/entry-points/plugin-common.js
- src/init-config.js
- src/login-init-app.js
- src/login-root-saga.js
- src/login-store.js
- src/login/InitResetForm/InitResetForm.js
- src/login/InitResetForm/InitResetForm.scss
- src/login/InitResetForm/InitResetForm_actions.js
- src/login/InitResetForm/InitResetForm_container.js
- src/login/InitResetForm/InitResetForm_reducer.js
- src/login/InitResetForm/InitResetForm_sagas.js
- src/login/LoginMain/LoginMain.js
- src/login/LoginMain/LoginMain.scss
- src/login/LoginMain/LoginMain_actions.js
- src/login/LoginMain/LoginMain_container.js
- src/login/LoginMain/LoginMain_reducer.js
- src/login/LoginMain/LoginMain_sagas.js
- webpack.config.js
Component with the form that triggers a reset password workflow. This form accepts an email, and sends it to the backend, which send an email to the provided address with a link to a form to actually reset the pasword.
> Eperez login app 8

- plugins/eduid_action.mfa/index.js
- plugins/eduid_action.mfa/public-path.js
- plugins/eduid_action.tou/index.js
- plugins/eduid_action.tou/public-path.js
- src/components/Email.js
- src/entry-points/login.js
- src/entry-points/plugin-common.js
- src/init-config.js
- src/login-init-app.js
- src/login-root-saga.js
- src/login-store.js
- src/login/InitResetForm/InitResetForm.js
- src/login/InitResetForm/InitResetForm.scss
- src/login/InitResetForm/InitResetForm_actions.js
- src/login/InitResetForm/InitResetForm_container.js
- src/login/InitResetForm/InitResetForm_reducer.js
- src/login/InitResetForm/InitResetForm_sagas.js
- src/login/LoginMain/LoginMain.js
- src/login/LoginMain/LoginMain.scss
- src/login/LoginMain/LoginMain_actions.js
- src/login/LoginMain/LoginMain_container.js
- src/login/LoginMain/LoginMain_reducer.js
- src/login/LoginMain/LoginMain_sagas.js
- src/login/Resetting/Resetting.js
- src/login/Resetting/Resetting.scss
- src/login/Resetting/Resetting_container.js
- webpack.config.js
base component for resetting the pw, after following the reset link
> Eperez login app 9

- plugins/eduid_action.mfa/index.js
- plugins/eduid_action.mfa/public-path.js
- plugins/eduid_action.tou/index.js
- plugins/eduid_action.tou/public-path.js
- src/components/Email.js
- src/entry-points/login.js
- src/entry-points/plugin-common.js
- src/init-config.js
- src/login-init-app.js
- src/login-root-saga.js
- src/login-store.js
- src/login/InitResetForm/InitResetForm.js
- src/login/InitResetForm/InitResetForm.scss
- src/login/InitResetForm/InitResetForm_actions.js
- src/login/InitResetForm/InitResetForm_container.js
- src/login/InitResetForm/InitResetForm_reducer.js
- src/login/InitResetForm/InitResetForm_sagas.js
- src/login/LoginMain/LoginMain.js
- src/login/LoginMain/LoginMain.scss
- src/login/LoginMain/LoginMain_actions.js
- src/login/LoginMain/LoginMain_container.js
- src/login/LoginMain/LoginMain_reducer.js
- src/login/LoginMain/LoginMain_sagas.js
- src/login/Resetting/Resetting.js
- src/login/Resetting/Resetting.scss
- src/login/Resetting/Resetting_actions.js
- src/login/Resetting/Resetting_container.js
- src/login/Resetting/Resetting_reducer.js
- src/login/Resetting/Resetting_sagas.js
- webpack.config.js
Grab the code from the URL and use it to retrieve configuration settings from the backend
> Eperez login app 10

- src/containers/Email.js
Fix DOM search to find the email
> did not find the email

- src/login/components/App/App.js
- src/login/components/LoginApp/LoginApp.js
.css ids and classes names of structural elements in `App.js` (equivalent to "Main" component of other apps) updated in line with example anatomy created in Figma
**Note this is not a fix of any styling. It should not change or break the styling.**
**Summary:**
- reduces number of divs in `App.js`:
- removes `<div>` with class `.horizontal-content-margin`(margin only needed when `<Notifications>` is not present)
- moves `.vertical-content-margin` from `<div>` in App.js  to `LoginApp.js`
> LOGIN: Updates naming of structural css in line with anatomy outlined in Figma

- src/components/DashboardMain.js
- src/components/Header.js
- src/login/styles/_DashboardMain.scss
- src/login/styles/_Header.scss
.css ids and classes names of structural elements in DashboardMain.js (equivalent to "Main" component of other apps) updated in line with example anatomy created in Figma
Summary:
- replace _div #dashboard-text_ -> _section #panel_  
- add _div #content_ -> _className .vertical-content-margin_ 
- footer replace outside of _section #content_
_Profile Before_
_Profile After_
> DASHBOARD MAIN: Updates naming of structural css in line with anatomy outlined in Figma 

- src/sagas/common.js
There is a problem submitting the personal data form, in that it also sends the eppn. This fixes it
> fix saving the personal data form

- package-lock.json
- package.json
A new React error appears in console since updating the React dependency this morning. As described in [this GitHub issue](https://github.com/facebook/react/issues/16504) the error is fixed by updating `"react-hot-loader": "4.3.11" -> "4.12.18"`.
> DEPENDECY: Fixes error message in console

- plugins/eduid_action.tou/component.js
- plugins/eduid_action.tou/style.scss
- src/components/ActionWrapper.js
.css ids and classes names of structural elements in ActionWrapper.js (equivalent to "Main" component of other apps) updated in line with example anatomy created in Figma
- Remove duplicated tagline and .dashboard-wrapper, #dashboard-text, .text-content
- replace h3 .tou-title to p .heading
_Before(Mater) and After_
_Before and After_
_Before and After_
> ACTIONWRAPPER: Updates naming of structural css in line with anatomy outlined in Figma 

- src/login/styles/_Notifications.scss
issue https://github.com/SUNET/eduid-front/issues/311
- Browser: Chrome
- Model:Desktop (Big screen)
- Before and After
- Browser: Chrome
- Model: Ipad(768)
- Before and After
> ERROR MESSAGE: Adjust positioning of error text for various devices

- src/components/PersonalData.js
- src/login/components/Inputs/CustomInput.js
- src/login/styles/_label.scss
- the plan is to reuse Input component for Register, Login, Settings and group management and design has been  created in figma.
- first step: created new component named "customInput" and refactored code based on "EduIdTextInput" component.
- separated `<Label/><RenderInput/><RenderHelpBlock/>`
- this is not a fix of any styling, next step will be fixing styling. 
- please check if code is readable and working properly? 
**This is not a fix of any styling.**
> INPUT: create custom input

- src/vetting-registry.js
A quick refactor of `<VerifyIdentity/>` to be able to follow more clearly how the vetting buttons are rendered and in particular see how `<OpenidConnect/>` works.
**Summary**: 
- This is by no means a perfect job just a quick restructure of a component that was an even greater  mess to begin with
- component now restructured into separate functions: 
```
<VerifyIdentity_Step1 />
<Number added> (if nin is verified) 
<AddNumber> (if nin is not verified) 
<AddNin/> (the nin input/display of added nin - which has its own complicated render logic that I am not going to touch now)
<VerifyIdentity_Step2 />
<VettingButtons>
``` 
**Note, as this is not a full path for group management, I will keep it separate from master and request that it is merged into a group management path branch**
**Next …
> VETTING: Refactor of <VerifyIdentity> to be able to better follow how vetting buttons render

- src/login/app_utils/checkForCookie.js
- src/login/components/App/DashboardApp/Settings/Groups.js
A refactor of the `<CookieChecker>`  functionality from component to a plain js function in `app_utils/`
**Summary:**
- A quick refactor of the cookie functionality to move it from `components/` to `app_utils/`:
- code rewritten as plain js function `checkForCookie()` 
- checkForCookie()` returns a boolean that shows `<Groups>` or not
- Should work the same as the previous PR (show or not based on cookie being present)
Note that `<OpenidConnect>` still uses `<CookieChecker>`so functionality will have to be duplicated in both places for now
> GROUPS: refactor of cookie functionality from component to plain .js function

- src/components/VerifyIdentity.js
- src/vetting-registry.js
Moving refactor of `VerifyIdentity` to master branch for further work. 
- This has already been [reviewed and merged](https://github.com/SUNET/eduid-front/pull/365) into the group management branch.
> VETTING: Adds restructure of VerifyIdentity component

- i18n/src/login/translation/messageIndex.json
- src/components/EduIDTextInput.js
- src/login/translation/languages/en.json
- src/login/translation/languages/sv.json
- src/login/translation/messageIndex.js
- src/login/translation/src/login/translation/messageIndex.json
I replaced back a translation of language options.
- English and Svenska
> SELECT LANGUAGE: Remove translation language options

- src/components/EduIDTextInput.js
> Revert master before updated Snyk

- i18n/src/login/translation/defaultMessages/userProfile.json
- i18n/src/login/translation/messageIndex.json
- src/components/Mobile.js
- src/login/components/Inputs/CustomInput.js
- src/login/styles/_Emails.scss
- src/login/styles/_anti-bootstrap.scss
- src/login/styles/_buttons.scss
- src/login/styles/_inputs.scss
- src/login/styles/_label.scss
- src/login/translation/defaultMessages/userProfile.js
- src/login/translation/languages/en.json
- src/login/translation/languages/sv.json
- src/login/translation/messageIndex.js
- src/login/translation/src/i18n-messages.json
- src/login/translation/src/login/translation/defaultMessages/userProfile.json
- src/login/translation/src/login/translation/messageIndex.json
Replace new customInput for Phone Form
----
before and after (with error message)@desktop 1200px
before and after (with error message)@mobile 320px
----
> INPUT: Implement custom input for phone form

- babel.config.js
- package-lock.json
- package.json
- src/login/components/App/DashboardApp/Settings/Groups/Groups.js
- src/login/components/DataTable/DataTable.js
- src/login/components/DataTable/DataTableRow/DataTableRow.js
- src/login/components/Wizard/WizardPanel.js
Adds logic to render create group wizard (to help guide the creation of a first group) and the "create group" button for subsequent creation of groups.  
**Summary**: 
1.  Work on existing `<Groups/>`: 
- Mock of upcoming component `<DataPanel/>` added as function (`RenderDataPanel`)
- `this.state.wizardCreateGroup` renamed to `this.state.firstGroup`
- Method `renderCreateButton` added to sets `state.firstGroup: false`
2. New component `<WizardPanel/>`:
- Handles rendering of the correct wizard at the right time:
- Mock of **create first group wizard** added as function (`RenderFirstGroupWizard`) - mock inline styling also applied for clarity, but many elements not functional
- In preparation for the **reply to first invite wizard**, the state `this.state = { firstInvite: true };` is …
> GROUP MANAGEMENT: Applies logic to render wizard vs Create Group button

- src/components/Email.js
- src/components/Emails.js
- src/login/app_utils/validation/validateEmail.js
Separated  validation code in `Email.js` and `Emails.js` for reuseability and to reduce code 
Please check the validation is still working.
next step, change file names(`Emails.js`->`Register.js`)(`Emalis.js`->`AddEmails.js`)
- Import `validateEmail` from `login/app_utils/validation/validateEmail`
- Remove validate code from Email.js/Emails.js
----
- Browser: Chrome
- Email.js
- Emails.js
----
> Separate validation for email(register)/emails(adding emails)

- src/actions/LookupMobileProofing.js
- src/components/LookupMobileProofing.js
- src/containers/LookupMobileProofing.js
- src/sagas/LookupMobileProofing.js
- src/tests/LookupMobileProofing-test.js
- src/vetting-registry.js
The vetting button has been unable to know if numbers are verified or not as a result the incorrect modal has been opening prompting users to add a number although numbers have been verified and ready for vetting. 
**Summary**: 
1. Connected component to redux store
- Added ` {...props}` to `<LookupMobileProofing />` listed in `src/vetting-registry.js` to allow props to flow from redux store to the modal
2. Added ability to check for primary number i component (and error handling if no numbers or no primary numbers)
```
if (phoneNumbers !== []) {
primaryNumber = phoneNumbers.some((num) => num.primary === true);
} 
```  
3. Checked that the POST request to vet via phone number works
- leaving console.logs in code to be able to keep an eye on this request in the near future
---
--- …
> VETTING BY PHONE: Fixing logic to handle modals to prompt user to add/verify a phone number

- src/components/RegisterEmail.js
- src/containers/Email.js
- src/login/components/RegisterEmail/RegisterEmail.js
We had decided to move the reviewed file to new location(login). so the old file(Email.js) in /src folder will be removed.
Already reviewed `Email.js` component in /src location. 
container, action, reducer still remain in /src
`Email.js` is renamed to `RegisterEmail.js` and move to /login/component/RegisterEmail.
**please check Register is working.**
> Rename Email to RegisterEmail and move location

- src/login/components/App/DashboardApp/Settings/Groups/Groups.js
- src/login/components/App/DashboardApp/Settings/Groups/GroupsContainer.js
- src/login/components/DataPanel/DataPanel.js
- src/login/components/DataPanel/EditDataBox.js
- src/login/components/DataPanel/ViewDataTable.js
- src/login/components/Wizard/WizardPanel.js
- src/login/styles/_Groups.scss
- src/login/styles/index.scss
This PR adds a `_Groups.scss` stylesheet and takes on all mock inline styling.
**Summary:**
1. Inline styles moved to stylesheet:
- The styling is not at its most refactored (as this is still under development)
- For now the styling has moved to a `_Groups.scss` stylesheet, but I expect the styling to be aligned with other updated elements (modals, inputs, table, etc) in the future
- To facilitate refactoring later, I will be giving similar styling similar names so that patterns can be easily identified 
2. Comments and console.logs removed 
> The group data has not yet been coupled to rendering logic, so this time state will have to be changed manually: 
> wizard: `<Groups /> state = {firstGroup: true}`
> view-mode: `<Groups /> state = {firstGroup: false }` (initial state)
> edit-mode: …
> GROUP MANAGEMENT: Adds Groups stylesheet for styling

- src/login/components/App/DashboardApp/Settings/Groups/Groups.js
- src/login/components/App/DashboardApp/Settings/Groups/GroupsContainer.js
- src/login/components/DataPanel/DataPanel.js
- src/login/components/DataPanel/EditDataBox.js
- src/login/components/DataPanel/EditMode.js
- src/login/components/DataPanel/ViewDataTable.js
- src/login/components/DataPanel/ViewMode.js
- src/login/components/Wizard/WizardPanel.js
- src/login/redux/reducers/getAllGroupsDataReducer.js
- src/login/redux/sagas/groups/allDataSaga.js
- src/login/styles/_Groups.scss
Previous versions of the groups functionality was mocked up in local state as proof of concept. Here the UI responds to the users actual data. 
**Summary:** 
1.  While `<Groups />` is requesting data there is a basic "Loading..." message that could be used for something
2. `<Groups />` renders `<WizardPanel/>` or `<DataPanel/>` depending on prop `firstGroup` 
-  `firstGroup` is determined in the GroupsContainer based on `member_of` and `owner_of` in the `/all-data` payload
-  If `props.firstGroup: true` user sees the wizard
-  If `props.firstGroup: false` user sees their data 
3. If there is group data it is renders a mock layout of groups that user is listed as `owner_of`
- `<ViewDataTable>` renders a mock layout of the group list
- `<Groups />` renders the create groups button
- …
> GROUP MANAGEMENT: Adds render logic to respond to user data

- src/login/components/LetterProofing/LetterProofing.js
- src/login/components/LetterProofing/LetterProofingContainer.js
- src/tests/LetterProofing-test.js
- src/tests/VerifyIdentity-test.js
- src/vetting-registry.js
Reviewed and improved files move to new location(login). 
so now LetterProofing component file from `src/component`  and container file from`src/containers` has been migrated to` /login/component/LetterProofing`
> Migrating letterProofing component and container 

- src/login/components/GroupManagement/GroupManagement.js
Issue https://github.com/SUNET/eduid-front/issues/516
> GROUPMANAGEMENT: FIx spelling error

- src/login/components/LookupMobileProofing/LookupMobileProofing.js
- src/login/components/LookupMobileProofing/LookupMobileProofingContainer.js
- src/tests/LookupMobileProofing-test.js
- src/vetting-registry.js
Reviewed and improved files move to new location(login).
so now LookupMobileProofing component file from `src/component` and container file from `src/containers` has been migrated to `/login/component/LookupMobileProofing`
> Migrating LookupmobileProofing component and container

- src/login/styles/_buttons.scss
I have fixed the issue https://github.com/SUNET/eduid-front/issues/501 and I have changed the accept button styling for "TOU".
---
- Before and after
- Before and after(hover effect)
- Before and after(TOU - hover effect)
> REGISTER: Cancel button text color and accept "TOU" hover effect to be changed

- src/errors-init-app.js
- webpack.staging.config.js
> Add initialConfigPlugin for webpackStaging.plugins

- src/login/translation/languages/sv.json
https://github.com/SUNET/eduid-front/issues/550
error spelling fix "DÖJL -> DÖLJ"
> SETTINGS/IDENTITY: Minor spelling

- src/components/Captcha.js
- src/components/ChangePasswordForm.js
- src/components/DeleteModal.js
- src/components/GenericConfirmModal.js
- src/login/components/Modals/ConfirmModal.js
- src/login/components/Modals/NotificationModal.js
- src/login/styles/_buttons.scss
Issue https://github.com/SUNET/eduid-front/issues/556
---
- Cancel button text color changed to Black
- Hover effect
---
> CHANGEPASSWORD : Cancel button text color to be changed 

- public/dashboard.html
- public/login.html
- public/signup.html
- webpack.config.js
- webpack.prod.config.js
- webpack.staging.config.js
Create new html files for signup, login, dashboard and errors in each environment (dev, staging, production)
---
- For testing in local (npm start) / [name]-bundle.dev.js / [name].dev.html
----
- For testing in staging (npm run build) / [name]-bundle.staging.js  / [name].staging.html
----
- For testing in production (npm run build-pro) / [name]-bundle.js / [name].html
---
> Create separate  HTML files and bundles

- .jenkins.yaml
- webpack.prod.config.js
- webpack.staging.config.js
Use old bundle names until we switch bundle loading mechanism
> Lundberg revert bundle names

- src/components/DashboardMain.js
- src/components/Settings.js
- src/containers/DashboardMain.js
- src/dashboard-root-saga.js
- src/login/redux/actions/addDataToStoreActions.js
- src/login/redux/reducers/groupsReducer.js
This PR adds a check for a specific cookie on load of the dashboard and sets the result in the redux store. The cookie status value in the store controls render of the group UI components and if the API calls in the rootSaga are made on load.
**Summary**: 
1. Set cookie status in redux store:
- `<DashboardMain/>` checks for cookie and sets result in state 
-  On mount`<DashboardMain/>` passes the cookie status via Container to the action of type `ADD_COOKIE_STATUS_TO_STORE`
- dispatch of `ADD_COOKIE_STATUS_TO_STORE` makes the reducer set the status in the redux store
2. `hasCookie` in redux store controls
- `<Settings.js/>`: render of the group management UI components 
- `dashboard-root-saga.js`: if group API calls are made on load 
**Known limitations**:
- For `<DashboardMain/>` the …
> GROUP MANAGEMENT: Add conditional for group management API calls on load

- src/login/app_config/login-rootSaga.js
- src/login/app_init/init_actions.js
- src/login/app_init/init_container.js
- src/login/app_init/init_reducer.js
- src/login/app_init/init_sagas.js
- src/login/redux/actions/postResetPasswordActions.js
This PR is for clean up code in init-files and add "postResetPasswordActions.js" for init container
> Clean up/Update init files

- src/login/components/GroupManagement/GroupNameForm.js
- src/login/components/LoginApp/Login/Login.js
- src/login/components/LoginApp/Login/LoginForm.js
This PR adds validation to the email input in the login form.
**Summary**: 
1. `LoginForm` combines two imported inputs:
- Email input from EmailForm with standard email validation
- Password input imported from GroupNameForm (as required in a combined form)
2. Added some initial html structure to `Login`
- Moved submit button to parent component outside of LoginForm
3. export input only from `GroupNameForm`
- Temporary change as the combined form requires import of input only (import of entire form not allowed)
**Known limitations:**
- no functionality other than validation of email address has been added
- the submit button does not work yet
- the input values are not passed anywhere
- the styling is not final
- behaviour of inputs not final
---
---
> LOGIN: Adds standard validation to email address values

- src/login/components/GroupManagement/EmailForm.js
- src/login/components/GroupManagement/GroupNameForm.js
- src/login/components/LoginApp/Login/Login.js
- src/login/components/LoginApp/Login/LoginForm.js
- src/login/styles/_Login.scss
- src/login/styles/_buttons.scss
- src/login/styles/_forms.scss
- src/login/styles/_inputs.scss
- src/login/styles/index.scss
- src/login/styles/variables.scss
- src/tests/Header-test.js
This PR adds styling to the login form.
**Summary**: 
1. Added login styles
- **NEW**: `_Login.scss` created and firat styles added
- Styles applied to Login and LoginForm
2. Removal of commented out code from stylesheets and unused variables 
**Known limitations**:
- no functionality other than validation of input values has been added
- the submit button does not work yet
- the input values are not passed anywhere
- behaviour of inputs not final
---
---
> LOGIN: Adds styling to login form

- src/login/app_config/login-rootSaga.js
- src/login/app_init/init_actions.js
- src/login/app_init/init_container.js
- src/login/app_init/init_reducer.js
- src/login/components/LoginApp/Login/Login.js
- src/login/components/LoginApp/Login/UsernamePw.js
- src/login/components/LoginApp/LoginApp.js
- src/login/redux/actions/addDataToStoreActions.js
- src/login/redux/actions/postRefLoginActions.js
- src/login/redux/reducers/loginReducer.js
- src/login/redux/sagas/login/postRefLoginSaga.js
- src/login/redux/sagas/login/postRefOnLoadSaga.js
- src/tests/Login-test.js
- src/tests/sagas/postRefToLogin-test.js
This PR adds an api call to the `/next` endpoint on load of the login app. Response from this endpoint informs the client of what steps in the login process the user needs to complete.
> Do not review in Safari at the moment
**Summary:**
1. API call to `/next` should only be possible if url is `/login/ref` 
- init_container: if url is `/login/` its `ref` will be extracted and added to the redux store
- login-rootSaga: after `GET_JSCONFIG_LOGIN_CONFIG_SUCCESS`, if a `ref` is saved in the redux store the `/next` api call will fire when `POST_LOGIN_REF_TO_NEXT` is dispatched 
2. The API call should fire if url is `/login/ref`
- LoginApp: dispatch `POST_LOGIN_REF_TO_NEXT` when `state.config.next_url` is updated (i.e. when config has successfully updated redux store)
- LoginApp: render `Login` …
> LOGIN: Adds api call to /next on load

- src/login/app_config/login-rootSaga.js
- src/login/app_init/init_actions.js
- src/login/app_init/init_container.js
- src/login/app_init/init_reducer.js
- src/login/components/LoginApp/Login/Login.js
- src/login/components/LoginApp/Login/LoginForm.js
- src/login/components/LoginApp/Login/UsernamePw.js
- src/login/components/LoginApp/LoginApp.js
- src/login/redux/actions/addDataToStoreActions.js
- src/login/redux/actions/postRefLoginActions.js
- src/login/redux/actions/postUsernamePasswordActions.js
- src/login/redux/reducers/loginReducer.js
- src/login/redux/sagas/login/postRefLoginSaga.js
- src/login/redux/sagas/login/postRefOnLoadSaga.js
- src/login/redux/sagas/login/postUsernamePasswordSaga.js
- src/login/redux/sagas/rootSaga/loginSagas.js
- src/login/styles/_buttons.scss
- src/tests/Login-test.js
- src/tests/sagas/postRefToLogin-test.js
This PR adds a submit event to the LoginForm button. The event collects the form values and passes posts them to the endpoint `/pw_auth`.
> You will need to use usernames and passwords from your database   
**Summary**: 
1. onSubmit event added to LoginForm
- UsernamePw: LoginFormButton is separated into a functional component and connected to loginForm
- LoginForm: submitUsernamePassword submit event dispatches `POST_USERNAME_PASSWORD`
2. api call to /pw_auth 
- **NEW**: postUsernamePasswordActions
- **NEW**: postUsernamePasswordSaga
- loginReducer updated to return state on `_SUCCESS`
> The second `/next` response will return further information about the users authentication
3. login-rootSaga refactored
- sagas related to login have been moved to separate folder …
> LOGIN: Adds Log in button submit event and API call to /pw_auth

- package-lock.json
- package.json
- src/login/components/App/App_reducer.js
- src/login/components/LoginApp/Login/UsernamePw.js
- src/login/redux/actions/loadingDataActions.js
- src/login/redux/sagas/login/postRefLoginSaga.js
- src/login/redux/sagas/login/postUsernamePasswordSaga.js
- src/tests/Login-test.js
This PR adds actions and a state in redux store to inform if an API call is ongoing or not.
> So far this check has only been applied to the `/pw_auth` endpoint  
**Summary**: 
1. Actions dispatched at start and end of saga 
- **NEW**: `LOAD_DATA_REQUEST` and `LOAD_DATA_COMPLETE` 
2. Redux state can inform the entire app
-  `state.app` has a `loading_data` state controlled by a boolean
---
---
> LOGIN: Adds actions to inform when an async API call start and finishes 

- package-lock.json
- package.json
- src/login/components/App/App_reducer.js
- src/login/components/LoginApp/Login/Login.js
- src/login/components/LoginApp/Login/MultiFactorAuth.js
- src/login/components/LoginApp/Login/TermsOfUse.js
- src/login/components/LoginApp/Login/UsernamePw.js
- src/login/redux/actions/loadingDataActions.js
- src/login/redux/reducers/loginReducer.js
- src/login/redux/sagas/login/postRefLoginSaga.js
- src/login/redux/sagas/login/postUsernamePasswordSaga.js
- src/tests/Login-test.js
This PR prepares the Login component to render different children based on the response from `/next`.
> during development the backend code will be received and stored, but a manual override will be used to control what is rendered
**Summary**:
1. Adds missing components:
- **NEW** `<TermsOfUse />` for the page to accept tou 
- **NEW** `<MultiFactorAuth />` for the page to user security key/freja eid
2. loginReducer.js: Adds in `action` and `target` from backend 
- code to dictate the next page is added but commented out for now
- hardcoded override has been added to manually control the render during development 
3.  Login.js: Adds logic to <Login/> render the correct page based on payload action from the backend
- **TEST** checks that the right child is rendered on its matching response …
> LOGIN: Adds in render based on /next response

- package-lock.json
- src/login/components/LoginApp/Login/Login.js
- src/tests/Login-test.js
- src/tests/sagas/postUsernamePasswordSaga-test.js
This PR adds some supplementary tests for: postUsernamePasswordSaga and Login.js.
**Summary**: 
1. **TEST**: For postUsernamePasswordSaga that makes a call  to `/pw_auth` 
- ensures that the required data  is sent
- checks that the action following the api call() is NEW_CSRF_TOKEN
2. **TEST**: Login component following the new routing 
- Adds tests to check that the pathname of the different children corresponds with an expected one
> LOGIN: additional tests for postUsernamePasswordSaga and Login

- src/login/components/LoginApp/Login/FrejaeID.js
- src/login/components/LoginApp/Login/MultiFactorAuth.js
- src/login/components/LoginApp/Login/SecurityKey.js
- src/login/components/LoginApp/Login/UsernamePw.js
This PR improves accessibility, specifically tab-navigation and screen reader experience (chromevox) on the multi-factor authentication page.
**Summary**:
1. `tabIndex="0"` added:
- To first paragraph under heading
- To security key option and to Freja eID+ option
**Known limitations:**
- no accessibility or screen reader functionality available during security key assertion
> LOGIN: Improved accessibility for multi-factor authentication page

- src/login/components/Inputs/PasswordInput.js
- src/login/components/LoginApp/Login/FrejaeID.js
- src/login/components/LoginApp/Login/MultiFactorAuth.js
- src/login/components/LoginApp/Login/SecurityKey.js
- src/login/components/LoginApp/Login/UsernamePw.js
- src/login/translation/languages/en.json
- src/login/translation/languages/sv.json
- src/login/translation/messageIndex.js
- src/login/translation/src/login/translation/messageIndex.json
This PR translates the placeholder in the password input.
> LOGIN: Adds translation to password placeholder

- src/tests/sagas/postResetPasswordSaga-test.js
This PR is for adding test for postResetPasswordSaga.
> RESETPASSWORD: Add tests for api call to /reset-password/

- src/login/app_config/login-rootSaga.js
- src/login/components/Inputs/InputToggleShowHide.js
- src/login/components/LoginApp/ResetPassword/ExtraSecurity.js
- src/login/components/LoginApp/ResetPassword/SetNewPassword.js
- src/login/redux/sagas/resetpassword/postExtraSecurityPhoneSaga.js
- src/login/redux/sagas/resetpassword/postSetNewPasswordExtraSecurityExternalMfaSaga.js
- src/login/redux/sagas/resetpassword/postSetNewPasswordExtraSecurityPhoneSaga.js
- src/login/redux/sagas/resetpassword/postSetNewPasswordExtraSecurityTokenSaga.js
- src/login/redux/sagas/resetpassword/postSetNewPasswordSaga.js
- src/login/redux/sagas/resetpassword/postVerifyEmailSaga.js
- src/login/styles/_ResetPassword.scss
- src/login/styles/_inputs.scss
- src/login/translation/defaultMessages/password.js
- src/login/translation/languages/en.json
- src/login/translation/languages/sv.json
- src/login/translation/src/login/translation/defaultMessages/password.json
- src/tests/ResetPassword-test.js
To ensure that the users understands that there new password is auto generated and non changeable,
The user is instructed to copy the generated password and past it in a "repeat new password" field before they can proceed with reset password.
- Added a input for new password that user only can read and copy from (non editable)
- Added validation, check if input is empty or if input value matches suggested_password
- Adjusted translate text for resetpw.set-new-password-description
- eng: A strong password has been generated for you. To proceed you will need to copy the password in to the Repeat new password field and click Accept Password.
- swe: Ett säkert lösenord har genererats till dig. För att komma vidare behöver du kopiera det till Repetera ditt nya lösenord och klicka Acceptera …
> RESETPASSWORD:  Copy/Paste to accept new password

- src/login/components/LoginApp/ResetPassword/PhoneCodeSent.js
- src/login/styles/_ResetPassword.scss
This PR is to change the button text from "SAVE" to "OK" and to add a cursor pointer as hover effect on the link (enter code)
---
---
> RESETPASSOWRD: Change button text to OK and add hover effect to cursor

- src/login/redux/sagas/resetpassword/postVerifyEmailSaga.js
- src/login/translation/defaultMessages/password.js
- src/login/translation/languages/en.json
- src/login/translation/languages/sv.json
- src/login/translation/src/login/translation/defaultMessages/password.json
Issue https://github.com/SUNET/eduid-front/issues/698
Issue https://github.com/SUNET/eduid-front/issues/707
> RESETPASSWORD: Rephrase the status message when email link has been sent

- src/login/components/LoginApp/ResetPassword/CountDownTimer.js
Found a issue in staging, when user has requested a phone code, an infinite loop error occurs in  console
> RESETPASSWORD: Fix issue infinite loop in console

- src/login/app_config/login-rootSaga.js
- src/login/components/LoginApp/ResetPassword/ResetPasswordMain.js
- src/login/redux/sagas/resetpassword/postSetNewPasswordExtraSecurityPhoneSaga.js
- src/tests/ResetPassword-test.js
Fixes #720 
---
- Now redirect to extra-security page
---
> RESETPASSWORD:  Redirect to extra security when phone code has expired

- src/components/AccountCreated.js
- src/components/ActionMain.js
- src/components/Captcha.js
- src/components/DashboardMain.js
- src/components/EmailInUse.js
- src/components/ResendCode.js
- src/login/components/RegisterEmail/RegisterEmail.js
- src/login/components/SwamidErrors/Errors.js
- src/login/styles/_base.scss
This PR is to fix stugled padding-top for content.
- change from vertical-content-margin to horizontal-content-margin for content
- adjust padding-top to 3rem for content
---
- before fix
- after fix
---
> SIGNUP: Adjust padding for the content

- src/components/NinForm.js
> IDENTITY: Add unique id for add-nin-button

- src/components/Emails.js
- src/login/components/Inputs/EmailInput.js
- src/login/components/LoginApp/ResetPassword/ResetPasswordMain.js
- src/login/components/RegisterEmail/RegisterEmail.js
Change place holder text`example@example.com` to `name@example.com`
> INPUT: Change email place holder text

- src/login/components/LoginApp/Login/SubmitSamlResponse.js
RelayState should be posted with SAMLResponse
> POST both parameters when login flow is complete

- src/login/components/Inputs/CustomInput.js
- src/login/components/Inputs/PasswordInput.js
> LOGIN: Sets id for password-input

- src/components/Header.js
- src/login/styles/_Header.scss
- src/login/styles/_buttons.scss
new design login/logout button for better user experience  
---
- Login button on signup page
- Login: hover effect
-  Login at mobile size
- Logout button on dashboard page
- Logout : hover effect
- Logout at mobile size
---
> HEADER: Update of login/logout button 

- src/login/components/Inputs/PasswordInput.js
- src/login/components/LoginApp/Login/UsernamePw.js
- src/login/components/LoginApp/Login/UsernamePwForm.js
This PR is to add the function of pressing "enter" when in the "input fields"
Before the enter button was toggling "show and hide" for the password.
Now by pressing enter in any input field will send the data.
> LOGIN: To enable posting data by pressing the "enter" button

- src/components/Security.js
removed invalid date format for safari
> ADVANCEDSETTINGS: Remove invalid date for safari

- webpack.staging.config.js
Add source map to the staging build to help debugging.
> add source map to staging build

- src/components/Security.js
this PR is for users that are working with a device that is not supporting window.Public credentials
> ADVANCEDSETTINGS: Add else statement for when window.PublicKeyCredential is false

- src/components/Security.js
> ADVANCEDSETTINGS: Prettier formatting for security component

- src/login/app_init/init_actions.js
- src/login/app_init/init_sagas.js
- src/login/components/App/App_actions.js
- src/login/components/App/App_reducer.js
- src/login/components/LoginApp/Login/MultiFactorAuth.js
- src/login/components/LoginApp/Login/SecurityKey.js
- src/login/components/LoginApp/Login/SubmitSamlResponse.js
- src/login/components/LoginApp/Login/TermsOfUse.js
- src/login/components/LoginApp/Login/UsernamePwForm.js
- src/login/components/LoginApp/LoginApp.js
- src/login/redux/actions/loginActions.js
- src/login/redux/reducers/loginReducer.js
- src/login/redux/sagas/login/postRefForWebauthnChallengeSaga.js
- src/login/redux/sagas/login/postTouVersionsSaga.js
- src/tests/sagas/postTouVersionsSaga-test.js
- src/tests/sagas/postUpdatedTouAcceptSaga-test.js
- src/tests/sagas/postUsernamePasswordSaga-test.js
- src/tests/sagas/postWebauthnFromAuthenticatorSaga-test.js
> Prettier formatting for login app

- src/login/redux/sagas/resetpassword/postVerifyEmailSaga.js
> RESETPASSWORD: Move dispatch action inside if clause

- src/login/redux/slices/resetPasswordSlice.js
Fixes #775
when we inplemented Redux toolkit , the phone number disappeared, now reinstated
> RESETPASSWORD: Reinstate the phone number where the code was sent

- src/components/Emails.js
- src/components/Mobile.js
> DASHBORD: Add focus for email and phone input

- src/components/Emails.js
- src/components/Mobile.js
> Fix spelling

- Makefile
As a first step, just disable building them. 
Later, we can remove all of plugins/, some config in package.json and buildPlugins.* in the root of the project.
> mfa and tou actions shouldn't be needed anymore

- src/login/components/LoginApp/ResetPassword/EmailForm.tsx
- src/login/components/LoginApp/ResetPassword/ResetPasswordMain.tsx
> bye, document query-selector

- src/login/components/LoginApp/Login/Login.tsx
- src/login/components/LoginApp/LoginApp.tsx
- src/login/components/LoginApp/ResetPassword/ResetPasswordMain.tsx
- src/login/redux/sagas/login/postRefLoginSaga.ts
- src/tests/ResetPassword-test.js
> bugfix login ref handling

- src/login/components/Notifications/Notifications.js
> Add span tag for notifation messages

- src/containers/VerifyIdentity.js
Fixed undefined props.hasVerifiedNin
> Correct props.hasVerifiedNin

- src/components/ChangePasswordForm.js
- src/login/translation/extractedMessages.json
- src/login/translation/languages/en.json
- src/login/translation/languages/sv.json
- src/login/translation/leftovers.tsx
> Use formattedMessage for custom change password help text

- src/components/Orcid.js
- src/login/styles/_AccountLinking.scss
> Adjust linked orcid table styling

- src/login/components/PersonalData/PersonalDataParent.tsx
> Correct personal_data entry initial value undefined

- src/components/Emails.js
- src/components/Mobile.js
- src/components/Security.js
- src/containers/Mobile.js
- src/containers/Security.js
- src/login/components/Inputs/EmailInput.js
- src/login/components/LetterProofing/LetterProofing.js
- src/login/components/LetterProofing/LetterProofingContainer.js
- src/login/components/LoginApp/ResetPassword/EmailForm.tsx
- src/login/components/RegisterEmail/RegisterEmail.js
- src/login/translation/extractedMessages.json
- src/login/translation/leftovers.tsx
- src/tests/LetterProofing-test.js
> fix placeholders

- src/login/translation/languages/sv.json
> Remove <b> tag from translation

- src/login/styles/_ResetPassword.scss
> add more padding-left for timer

- src/login/components/LoginApp/ResetPassword/PhoneCodeSent.tsx
- src/login/styles/_ResetPassword.scss
> Eunju remove extra click phone code

- src/reducers/PersonalData.ts
> Add eppn for updatePersonalData

- src/login/styles/_Nins.scss
- src/login/translation/extractedMessages.json
- src/login/translation/languages/en.json
> Eunju remove curly bracket, adjust styling for vetting by post

- src/components/Security.js
- src/login/styles/_Security.scss
> Add cookieChecker to hide the platform auth button

- src/login/translation/languages/en.json
- src/login/translation/languages/sv.json
> Remove html tag from login.mfa.secondary-option.button

- src/components/Ladok.tsx
- src/login/translation/extractedMessages.json
> Add FormattedMessage for Link your account to Ladok

- src/login/components/PersonalData/PersonalDataForm.tsx
- src/login/styles/_PersonalData.scss
- src/login/styles/_buttons.scss
- src/login/styles/_inputs.scss
Replaced/refactored folkbokförings name-check button with related tweaks (hint => help-text, help-box spacing, grid spacing etc) on inställningar page.
> Carina folkbokföringsknapp

- src/login/styles/_base.scss
found a code that interfered with the custom scrollbar
the interfering code has been commented out for test and if all working the interfering code will be removed
> Fix scrollbar 

- src/components/Security.js
- src/login/components/LoginApp/ResetPassword/ResetPasswordLayout.tsx
- src/login/components/PersonalData/PersonalDataParent.tsx
- src/login/styles/_Groups.scss
- src/login/styles/_Login.scss
- src/login/styles/_ResetPassword.scss
- src/login/styles/_buttons.scss
> minor styling

- src/login/translation/extractedMessages.json
> LETTERPROOFING: Make translations

- src/components/Header.tsx
> Fix link to main page on login

- src/components/DashboardMain.js
- src/components/Header.tsx
- src/components/SignupMain.js
- src/login/components/App/App.tsx
> Use props for rendering login, register, logout buttons

- src/login/components/Footer/Footer.tsx
- src/tests/Footer-test.js
> FOOTER: Replace  a tag for selected language

- src/login/translation/extractedMessages.json
> Extract translation

- src/login/components/RegisterEmail/RegisterEmail.js
> Add onSubmit for register

- src/components/Header.tsx
- src/login/styles/_Footer.scss
- src/login/styles/_Header.scss
- src/login/styles/_base.scss
- src/login/styles/_typography.scss
> edits paddings in header/footer

- src/login/styles/_Footer.scss
- src/login/styles/_Login.scss
> Frontend minor fix 

- src/login/components/LoginApp/Login/TermsOfUse.tsx
- src/login/translation/extractedMessages.json
> TOU: add security keys

- src/dashboard-root-saga.js
- src/login/app_config/login-rootSaga.js
- src/login/components/LoginApp/Login/UsernamePw.tsx
- src/signup-root-saga.js
- Warning 1: Removed type="submit" for login on other device button 
- Warning 2:  import { all } from "redux-saga/effects";
> LOGIN: fix warning messages in console.log

- src/login/components/LoginApp/Login/ResponseCodeForm.tsx
- src/login/styles/_Login.scss
> Position change login and cancel buttons

- src/login/components/LoginApp/Login/UsernamePw.tsx
> Fix buttonStyle to buttonstyle

- src/login/components/LoginApp/Login/NewDevice.tsx
- src/login/components/LoginApp/Login/UsernamePw.tsx
- src/login/styles/_AccountLinking.scss
- src/login/styles/_Emails.scss
- src/login/styles/_Login.scss
- src/login/styles/_forms.scss
- src/login/styles/_img.scss
- src/login/styles/_inputs.scss
- src/login/styles/_links.scss
- src/login/styles/_modals.scss
- src/login/translation/extractedMessages.json
>  editing known device styling 

- src/login/styles/_Login.scss
> Make login with other device responsive

- src/login/components/LoginApp/Login/UseOtherDevice1.tsx
- src/login/components/LoginApp/Login/UseOtherDevice2.tsx
Add a span with the response code in "plain text", for easier use in tests.
> device2 developer info

- .vscode/settings.json
- src/login/components/LoginApp/Login/LoginAtServiceInfo.tsx
- src/login/components/LoginApp/Login/MultiFactorAuth.tsx
- src/login/components/LoginApp/Login/TermsOfUse.tsx
- src/login/components/LoginApp/Login/UsernamePw.tsx
- src/login/styles/_Login.scss
- src/login/translation/extractedMessages.json
> add service info

- src/components/SignupMain.tsx
> Remove , in signup

- src/globals.js
- src/login/components/Footer/Footer.tsx
- src/login/translation/index.tsx
Also simplify AVAILABLE_LANGUAGES into a straight object instead of a
list of lists.
> fix bug with figuring out the locale from the browser preference

- src/login/translation/defaultMessages/security.tsx
- src/login/translation/extractedMessages.json
added two new messages for security keys
> added two new messages for security keys

- src/components/Emails.tsx
- src/login/styles/_ResetPassword.scss
- src/login/styles/_inputs.scss
- src/login/translation/extractedMessages.json
removed check icon
removed help text (email address)
> Frontend translation issues

- src/login/styles/_ResetPassword.scss
> Reset password: Remove p tag

- src/components/DashboardNav.tsx
- src/login/styles/_DashboardMain.scss
- src/login/styles/_typography.scss
Introducing the term "dashboard" to users..
> Tighter dashboard nav with heading

- src/apis/eduidLogin.ts
- src/components/Phones.tsx
- src/login/components/LoginApp/Login/ResponseCodeForm.tsx
Styling help to make it look more like an error message would be appreciated :)
> show a message when the user supplies the incorrect response code

- src/login/components/LoginApp/Login/ResponseCodeForm.tsx
- src/login/styles/_Login.scss
> Reuse validation error styling

- src/login/translation/defaultMessages/userProfile.js
- src/login/translation/extractedMessages.json
> Add two error messages

- src/login/components/LoginApp/Login/UsernamePw.tsx
- src/login/components/LoginApp/ResetPassword/PhoneCodeSent.tsx
- src/login/translation/extractedMessages.json
> removed logging in text, added placeholder for phone confirmation code input

- src/components/Security.js
- src/login/styles/_Security.scss
- src/login/styles/_typography.scss
Replaced interactive-element font with variant of base font for nav heading.
Replaced heading with label in advanced security settings.
> Font/ element swap

- src/components/Eidas.tsx
> Update in accordance with feedback

- src/components/Eidas.tsx
- src/login/translation/extractedMessages.json
> reinstate freja helptext

- src/components/Orcid.js
- src/login/components/LoginApp/Login/UsernamePw.tsx
- src/login/components/LoginApp/ResetPassword/SetNewPassword.tsx
- src/login/components/PersonalData/PersonalDataForm.tsx
- src/login/components/PersonalData/PersonalDataParent.tsx
- src/login/styles/_AccountLinking.scss
- src/login/styles/_Emails.scss
- src/login/styles/_Errors.scss
- src/login/styles/_Groups.scss
- src/login/styles/_Login.scss
- src/login/styles/_PersonalData.scss
- src/login/styles/_ResetPassword.scss
- src/login/styles/_buttons.scss
- src/login/styles/_forms.scss
- src/login/styles/_img.scss
- src/login/styles/_inputs.scss
- src/login/styles/_timer.scss
Edit personal data form, heading, button update
Reuse refactor of help-text, required, button-pair, btw-icon, svg overrides
Change pw icon-only edit
> Frontend tou style

- src/components/Security.js
- src/login/components/LoginApp/Login/FrejaeID.tsx
- src/login/components/LoginApp/Login/SecurityKey.tsx
- src/login/styles/_Login.scss
- src/login/styles/_base.scss
- src/login/styles/_forms.scss
- src/login/styles/_typography.scss
- src/login/translation/defaultMessages/login.js
Verify options helptext,
semantic html,
responsiveness,
refactored/reused css,
new translations,
helptext for security keys advanced settings.
> Frontend verify button text

- src/login/components/LoginApp/Login/TermsOfUse.tsx
- src/login/styles/_Login.scss
- src/login/styles/_lists.scss
- src/login/styles/_modals.scss
- src/login/styles/_typography.scss
- src/login/translation/languages/sv.json
Aligned login terms of use to modal and general site styling,
removed unnecessary styling,
tweaked responsive lead styling.
> Adjusted login tou styles, .lead tweaks

- src/components/ChangePasswordDisplay.tsx
- src/components/DeleteAccount.js
- src/login/styles/_Nins.scss
- src/login/styles/_buttons.scss
Consistent link-style under dashboard settings tabs, to open modals etc. 
Tweaked transtion duration.
> Carina dashboard links

- src/login/components/LoginApp/Login/UsernamePw.tsx
- src/login/styles/_Header.scss
- src/login/styles/_Login.scss
- src/login/styles/_base.scss
- src/login/styles/_inputs.scss
- src/login/styles/_links.scss
Structured login html with fieldsets and grouped links
Moved vertical padding to panel - to match landingpage
login css outdated updates
Attempt att non-jumping non-valid forms
> Carina post html edit edits

- .eslintrc.js
- src/login/components/LoginApp/ResetPassword/ExtraSecurity.tsx
- src/login/components/LoginApp/ResetPassword/GoBackButton.tsx
- src/login/components/LoginApp/ResetPassword/PhoneCodeSent.tsx
- src/login/components/LoginApp/ResetPassword/SetNewPassword.tsx
- src/login/redux/sagas/resetpassword/postExtraSecurityPhoneSaga.ts
Use EduIDButton from GoBackButton, and refactor two more forms to use Final Form.
> Some more refactoring of Reset Password.

- src/components/ChangePassword.tsx
> correct url when user cancels or completes change of password process

- src/components/Emails.tsx
- src/login/components/Inputs/EmailInput.tsx
- src/login/translation/extractedMessages.json
> Fix email placeholder

- src/login/app_utils/validation/validatePersonalData.js
- src/login/components/Inputs/CustomInput.tsx
- src/login/components/LoginApp/Login/UsernamePw.tsx
- src/login/components/PersonalData/PersonalDataForm.tsx
- src/login/components/PersonalData/PersonalDataParent.tsx
- src/login/styles/_PersonalData.scss
- src/login/styles/_forms.scss
- src/login/translation/defaultMessages/generalApp.js
- src/login/translation/defaultMessages/userProfile.js
- src/login/translation/extractedMessages.json
- src/login/translation/leftovers.tsx
1. removed display name from settings
2. add fieldset to give more space between error message and labels
3. replace injectintl with formattedmessages
> Removed display name

- src/login/translation/defaultMessages/password.js
- src/login/translation/extractedMessages.json
> fix correct translation resetpw

- src/components/NotificationTip.tsx
- src/components/Notifications.tsx
- src/login/styles/_DashboardMain.scss
- src/login/styles/_Emails.scss
- src/login/styles/_Errors.scss
- src/login/styles/_Footer.scss
- src/login/styles/_Groups.scss
- src/login/styles/_Ladok.scss
- src/login/styles/_Login.scss
- src/login/styles/_Nins.scss
- src/login/styles/_Notifications.scss
- src/login/styles/_PersonalData.scss
- src/login/styles/_ResetPassword.scss
- src/login/styles/_SignupMain.scss
- src/login/styles/_Splash.scss
- src/login/styles/_anti-bootstrap.scss
- src/login/styles/_base.scss
- src/login/styles/_buttons.scss
- src/login/styles/_figure.scss
- src/login/styles/_forms.scss
- src/login/styles/_img.scss
- src/login/styles/_inputs.scss
- src/login/styles/_label.scss
- src/login/styles/_links.scss
- src/login/styles/_modals.scss
- src/login/styles/_reactSelect.scss
- src/login/styles/_tables.scss
- src/login/styles/_timer.scss
- src/login/styles/_typography.scss
- src/login/styles/variables.scss
Fewer colors and hopefully understandable names.
Valid colors, all texts on backgrounds (links, buttons, help-text, notifications, error-texts..).
Solid notification dot, instead of uncentered.
Thicker lead line to distinguish from in-page dividers.
Reusing framework behaviour in more aligned notification bar. 
Tweaks on buttons, e.g. height, spacing and letter-spacing for readability.
Gray instead light-orange on non-editable fields eg suggested pw, for consistency.
Tightening responsive Dashboard menu and experimenting with flex for desktop - this might look dumb!
> Accessible colors update

- src/login/components/Inputs/EmailInput.tsx
- src/login/components/LoginApp/Login/UsernamePw.tsx
- src/login/components/LoginApp/ResetPassword/EmailForm.tsx
- src/login/components/LoginApp/ResetPassword/ResetPasswordEnterEmail.tsx
- src/login/components/LoginApp/ResetPassword/ResetPasswordRequestEmail.tsx
- src/login/redux/slices/resetPasswordSlice.ts
- src/tests/login/LoginResetPassword-test.tsx
> remember user-entered e-mail, and ask for confirmation before sending

- src/login/components/LoginApp/ResetPassword/ExtraSecurity.tsx
- src/login/components/LoginApp/ResetPassword/ExtraSecurityToken.tsx
- src/login/components/LoginApp/ResetPassword/PhoneCodeSent.tsx
- src/login/components/LoginApp/ResetPassword/ResetPasswordLayout.tsx
- src/login/components/LoginApp/ResetPassword/ResetPasswordSuccess.tsx
- src/login/components/LoginApp/ResetPassword/SetNewPassword.tsx
- src/login/styles/_ResetPassword.scss
- src/login/styles/_buttons.scss
Mainly adapted to updates css from other areas.
> Carina style edits resetpw

- src/login/translation/extractedMessages.json
> extract messages

- src/login/components/LoginApp/Login/UsernamePw.tsx
- src/login/components/LoginApp/ResetPassword/EmailForm.tsx
- src/login/redux/slices/resetPasswordSlice.ts
- src/tests/login/LoginResetPassword-test.tsx
> RESETPASSWORD: ensure that an empty email input will direct user to "reset password" 

- src/login/components/PersonalData/PersonalDataForm.tsx
> Add span tag for language value

- src/components/Header.tsx
- src/components/Orcid.tsx
- src/login/components/Footer/Footer.tsx
- src/login/components/LoginApp/ResetPassword/EmailLinkSent.tsx
- src/login/components/LoginApp/ResetPassword/ResetPasswordRequestEmail.tsx
- src/login/translation/extractedMessages.json
Accesible logos,
redundant class,
make translation.
> Orcidbtn alt text

- src/login/components/LoginApp/ResetPassword/GoBackButton.tsx
- src/login/components/LoginApp/ResetPassword/ResetPasswordRequestEmail.tsx
> RESETPASSWORD: Prevent that the user is redirected to the previous page, when user changes language

- src/login/components/PersonalData/PersonalDataForm.tsx
- src/login/styles/_forms.scss
- src/login/translation/extractedMessages.json
Added fieldset legend for language radiogroup.
> Language radio legend

- public/dashboard.html
- src/components/ChangePasswordDisplay.tsx
> Rename title for dashboard app

- src/login/styles/_Ladok.scss
- src/login/styles/_base.scss
- src/login/styles/_buttons.scss
- src/login/styles/_forms.scss
Spacing and flex feedback - leading to minor ladok, button and utility class css edits/refactoring.
> Carina panel spacing

- src/login/components/PersonalData/PersonalDataForm.tsx
- src/login/components/PersonalData/PersonalDataParent.tsx
> Add missing validation for personal data and correct checking personal data names

- src/login/translation/defaultMessages/userProfile.tsx
- src/login/translation/extractedMessages.json
> Specific error message when adding security key

- src/login/components/PersonalData/PersonalDataForm.tsx
> Reinstated id for language radiobutton

- src/components/VerifyIdentity.tsx
> Correct order of hooks

- src/components/VerifyIdentity.tsx
> Fix for accordion visibility

- src/components/Notifications.tsx
- src/login/components/LoginApp/Login/UsernamePw.tsx
> Remove success status message

- src/components/Emails.tsx
- src/components/LetterProofing.tsx
- src/components/Phones.tsx
- src/login/components/LoginApp/ResetPassword/PhoneCodeSent.tsx
- src/login/translation/defaultMessages/generalApp.tsx
- src/login/translation/defaultMessages/userProfile.tsx
- src/login/translation/extractedMessages.json
- src/login/translation/leftovers.tsx
- src/tests/LetterProofing-test.tsx
> change texts, Confirmation code -> code

- src/login/translation/defaultMessages/errors.tsx
- src/login/translation/defaultMessages/generalApp.tsx
- src/login/translation/defaultMessages/password.tsx
- src/login/translation/defaultMessages/userProfile.tsx
- src/login/translation/extractedMessages.json
- src/login/translation/leftovers.tsx
> change text verification code -> code

- src/apis/eduidEidas.ts
- src/components/ExternalReturnHandler.tsx
- src/components/LoginExternalReturnHandler.tsx
- src/login/components/LoginApp/Login/FrejaeID.tsx
- src/login/components/LoginApp/Login/Login.tsx
- src/login/components/LoginApp/Login/MultiFactorAuth.tsx
- src/login/components/LoginApp/Login/SecurityKey.tsx
- src/login/components/LoginApp/LoginApp.tsx
- src/login/translation/defaultMessages/errors.tsx
- src/login/translation/defaultMessages/login.tsx
Changes to use a new backend API endpoint, and restores displaying of error messages from the login process.
> login freja update

- src/components/ChangePasswordCustom.tsx
- src/components/ChangePasswordSuggested.tsx
- src/components/EduIDTextInput.tsx
- src/login/components/Inputs/CustomInput.tsx
- src/login/components/Inputs/PasswordInput.tsx
- src/login/components/LoginApp/Login/UsernamePw.tsx
> Add/correct autoComplete

- src/login/translation/defaultMessages/register.tsx
> Add signup error messages from backend

- src/components/AccountCreated.tsx
- src/components/Captcha.tsx
- src/components/CodeVerified.tsx
- src/components/Signup/SignupApp.tsx
- src/components/Signup/SignupCaptcha.tsx
- src/components/Signup/SignupCaptchaForm.tsx
- src/components/Signup/SignupEmailForm.tsx
- src/components/Signup/SignupEnterCode.tsx
- src/components/Signup/SignupUserCreated.tsx
- src/login/components/LoginApp/Login/UseOtherDevice1.tsx
- src/login/styles/_PersonalData.scss
- src/login/styles/_SignupMain.scss
- src/login/styles/_Splash.scss
- src/login/styles/_buttons.scss
- src/login/styles/_figure.scss
- src/login/styles/_inputs.scss
- src/tests/Captcha-test.tsx
- src/tests/signup/SignupMain-test.tsx
> first version of new signup styling

- src/login/components/LoginApp/Login/NewDevice.tsx
- src/login/styles/_buttons.scss
- src/login/styles/_inputs.scss
Letting handle get all space it needs in flexed parent.
> Toggle full width responsive

- package-lock.json
- package.json
- src/apis/eduidPersonalData.ts
- src/apis/eduidSvipe.ts
- src/commonConfig.ts
- src/components/ExternalReturnHandler.tsx
- src/components/VerifyIdentity.tsx
- src/login/styles/_figure.scss
- src/login/styles/_tables.scss
- src/login/translation/defaultMessages/svipe.tsx
- src/tests/Svipe-test.tsx
> Introduce svipe

- src/components/Signup/SignupEnterCode.tsx
- src/login/translation/extractedMessages.json
> edit instruction signup

- src/login/components/Footer/Footer.tsx
- src/login/translation/extractedMessages.json
> Change copyright 2023

- src/components/Settings.tsx
- src/components/VerifyIdentity.tsx
- src/login/translation/extractedMessages.json
> Fix untranslated breadscrumbs texts

- src/components/VerifyIdentity.tsx
- src/login/components/Inputs/InputWrapper.tsx
- src/login/components/PersonalData/PersonalDataForm.tsx
> Eunju fix accessibility 

- src/components/Security.tsx
> Fix issue, request crendetials when crendentilas length is empty

- src/components/AccordionItemTemplate.tsx
- src/components/Recommendations.tsx
> add uniq id for accordion

- src/login/styles/_DashboardMain.scss
- src/login/styles/_SignupMain.scss
> minor styling fix

- src/components/Header.tsx
- src/components/Signup/SignupEmailForm.tsx
- src/login/components/LoginApp/Login/MultiFactorAuth.tsx
- src/login/components/LoginApp/Login/UsernamePw.tsx
- src/login/components/LoginMain.tsx
- src/login/styles/_Header.scss
- src/login/styles/_Login.scss
> Adjust html structure for login

- src/components/ChangePasswordCustom.tsx
- src/components/ChangePasswordSuggested.tsx
- src/components/EduIDTextInput.tsx
- src/components/Notifications.tsx
- src/components/PasswordStrengthMeter.tsx
- src/components/Phones.tsx
- src/login/components/Inputs/EmailInput.tsx
- src/login/components/Inputs/InputWrapper.tsx
- src/login/components/LoginApp/ResetPassword/ExtraSecurityToken.tsx
- src/login/components/LookupMobileProofing/LookupMobileProofing.tsx
- src/login/translation/defaultMessages/errors.tsx
- src/login/translation/defaultMessages/userProfile.tsx
- src/login/translation/extractedMessages.json
- src/login/translation/index.tsx
> Use react intl

- src/components/Phones.tsx
- src/components/Recommendations.tsx
- src/components/VerifyIdentity.tsx
- src/login/components/LoginApp/Login/UsernamePw.tsx
- src/login/components/LookupMobileProofing/LookupMobileProofing.tsx
- src/login/styles/_Login.scss
- src/login/translation/extractedMessages.json
> fix uncaught type error

- src/login/components/PersonalData/PersonalDataForm.tsx
> when language changes in the form, update the language in the store

- src/components/AccountId.tsx
- src/entry-points/dashboard.tsx
- src/globals.ts
- src/login/components/Footer/Footer.tsx
- src/login/components/PersonalData/PersonalDataForm.tsx
- src/reducers/PersonalData.ts
- src/tests/AdvancedSettings-test.tsx
> eppn is missing after postPersonalData request, language is not updated when user reload the page

- src/login/components/LoginApp/Login/FrejaeID.tsx
- src/login/styles/_Login.scss
- src/login/translation/defaultMessages/errors.tsx
- src/login/translation/extractedMessages.json
> Decrease h3 font size, add proofing.malformed_identity error msg

- src/login/components/LoginApp/Login/UsernamePw.tsx
- src/login/translation/extractedMessages.json
> remove space before username

- src/login/translation/defaultMessages/errors.tsx
- src/login/translation/extractedMessages.json
> add attribute missing error msg

- src/components/Signup/SignupUserCreated.tsx
- src/login/translation/extractedMessages.json
> signupUserCreated: improve the paragraph text

- src/login/translation/defaultMessages/errors.tsx
- src/login/translation/extractedMessages.json
> Eunju add http error

- .github/workflows/run-tests.yaml
- src/apis/eduidLadok.ts
issue: request unlink-user get HTTP 405 error
> Fix issue: unlink-user

- package-lock.json
- package.json
> Install audit ci

- src/components/ChangePassword.tsx
- src/components/DashboardBreadcrumbs.tsx
- src/components/DashboardMain.tsx
- src/components/ExternalReturnHandler.tsx
- src/components/NameDisplay.tsx
- src/components/NinDisplay.tsx
- src/login/components/LookupMobileProofing/LookupMobileProofing.tsx
- src/tests/DashboardMain-test.tsx
- src/tests/DashboardStart-test.tsx
- src/tests/helperFunctions/DashboardTestApp-rtl.tsx
> rename url profile -> start

- src/components/ChangePassword.tsx
- src/components/DashboardBreadcrumbs.tsx
- src/components/DashboardMain.tsx
- src/components/ExternalReturnHandler.tsx
- src/components/NameDisplay.tsx
- src/components/NinDisplay.tsx
- src/login/components/LookupMobileProofing/LookupMobileProofing.tsx
- src/tests/DashboardMain-test.tsx
- src/tests/DashboardStart-test.tsx
- src/tests/helperFunctions/DashboardTestApp-rtl.tsx
> Url change, Start -> Profile

- src/login/translation/defaultMessages/userProfile.tsx
- src/login/translation/extractedMessages.json
> add phone captcha error messages

- src/apis/eduidPhone.ts
- src/components/Phones.tsx
- src/components/Signup/SignupCaptcha.tsx
- src/login/components/Modals/ConfirmModal.tsx
- src/login/styles/_buttons.scss
- src/login/styles/_modals.scss
- src/reducers/Phones.ts
> captcha for phone confirmation

- src/components/Eidas.tsx
- src/components/Emails.tsx
- src/components/LetterProofing.tsx
- src/components/Phones.tsx
- src/components/Security.tsx
- src/login/components/LoginApp/ResetPassword/EmailLinkSent.tsx
- src/login/components/Modals/ConfirmModal.tsx
- src/login/components/Modals/NotificationModal.tsx
- src/machines/ResetPasswordMachine.ts
- src/machines/ResetPasswordMachine.typegen.ts
- src/tests/Phones-test.tsx
> Call to action with submit enter, add tests for phones component

- src/components/Eidas.tsx
> Fixed use frejaeID  button not working

- src/components/Phones.tsx
- src/components/Signup/SignupCaptchaForm.tsx
> Addition of Captha's placeholder

- src/login/components/LoginApp/ResetPassword/ResetPasswordEnterEmail.tsx
- src/login/translation/defaultMessages/password.tsx
- src/login/translation/extractedMessages.json
> Add Event,  Return to ResetPasswordEnterEmail page

- src/components/ChangePassword.tsx
- src/components/Security.tsx
- src/login/translation/extractedMessages.json
> Eunju remove ids formattedmessage

- src/components/Phones.tsx
- src/login/components/Modals/ConfirmModal.tsx
> Clear form input when the modal closes 

- src/components/Dashboard/Eidas.tsx
- src/components/Dashboard/LetterProofing.tsx
- src/components/Login/SecurityKey.tsx
- src/components/Login/TermsOfUse.tsx
- src/components/Login/UseOtherDevice1.tsx
> <> -> <Fragment />

- src/components/Login/ResponseCodeForm.tsx
- src/components/Signup/SignupEnterCode.tsx
I have refactored the code to ensure that inputs with existing values are replaced with new values when the user enters a new code. Additionally, I have implemented a feature that allows users to copy and paste the code.
1. Use the keyboard arrows to move the value to its existing position, and then type in the new value to see if it changes.
2. Attempt to copy and paste the email code.
3. When you copy and paste, you should have the ability to observe the value for 1 seconds before it auto-submits.
> SIGNUP: Improved value handling and copy paste support

- src/translation/defaultMessages/signup.tsx
- src/translation/extractedMessages.json
> Make translations

- src/translation/defaultMessages/resetPassword.tsx
- src/translation/extractedMessages.json
> Reinstate resetpw.send-sms-success

- src/components/Login/ResponseCodeForm.tsx
- src/tests/signup/SignupMain-test.tsx
> SIGNUP: Display a spinner during form submission and while waiting for the response

- src/components/Dashboard/DashboardStart.tsx
- src/components/Dashboard/VerifyIdentity.tsx
> Remove pre expanded for accordion

- src/components/Dashboard/AdvancedSettings.tsx
- src/components/Dashboard/DashboardStart.tsx
- src/tests/DashboardMain-test.tsx
- src/tests/DashboardStart-test.tsx
> Moved eppn to the advanced settings page

- src/apis/common.ts
> Clears remaining failure messages after success

- src/apis/common.ts
> Remove ClearNotification

- src/components/Login/UsernamePw.tsx
> Clear notification when fetchUsernamePassword.fulfilled

- src/apis/eduidPhone.ts
- src/components/Dashboard/Phones.tsx
- src/slices/Phones.ts
> Remove resend endpoint

- img/flags/FOvalIndigo.svg
- src/components/Dashboard/Recommendations.tsx
- src/components/Dashboard/VerifyIdentity.tsx
- src/styles/_accordion.scss
- accordion handle icons for clarity, Freja and others on recommendations and identity
- handled long accordion titles without overlap
> Catja verification icons

- Makefile
- src/commonConfig.ts
- src/components/Dashboard/ChangePasswordDisplay.tsx
> token_service_url -> authn_url

- src/components/Help.tsx
- src/translation/extractedMessages.json
> edited help text after feedback

- src/components/Dashboard/Eidas.tsx
- src/tests/Eidas-test.tsx
Updated Freja terminology (without eid) in non-translated links/button texts
> Updated non-translated Freja terminologi

- src/translation/defaultMessages/resetPassword.tsx
> Reinstate chpass.different-repeat

- src/translation/extractedMessages.json
> Make translate

- src/translation/defaultMessages/common.tsx
- src/translation/extractedMessages.json
> Add common.locked_identity_not_matching

- src/components/Help.tsx
Just added basic info on bankid use in FAQ
> Cat bankid faq

- src/apis/eduidBankid.ts
- src/apis/eduidLogin.ts
- src/components/Common/Security.tsx
- src/components/Dashboard/VerifyIdentity.tsx
- src/components/Login/LoginExternalReturnHandler.tsx
- src/components/Login/MultiFactorAuth.tsx
- src/components/Login/SwedishEID.tsx
- src/styles/_Login.scss
- src/styles/_accordion.scss
- src/styles/_buttons.scss
- src/styles/_tables.scss
- src/tests/Security-test.tsx
- src/translation/defaultMessages/login.tsx
- src/translation/extractedMessages.json
- Added bankID as an MFA option
- Added the ability to verify security keys with BankID
> Added bankID as an MFA option

- src/components/ResetPassword/HandleExtraSecurities.tsx
- src/components/ResetPassword/SetNewPassword.tsx
- src/slices/ResetPassword.ts
- src/tests/login/LoginResetPasswordExtraSecurity-test.tsx
- src/translation/extractedMessages.json
> add bankid for resetpassword

- src/apis/eduidBankid.ts
- src/translation/extractedMessages.json
> Add success msg

- src/components/Common/ExternalReturnHandler.tsx
- src/translation/extractedMessages.json
> serializable error fix, add bankid.identity_verify_success

- src/components/Common/Security.tsx
> add a redirect URL, when the user encounters a 'eidas.must_authenticate' or  'bankid.must_authenticate' error

- src/components/Help.tsx
- src/translation/extractedMessages.json
Just added paragraph at end of faq for adjusted phone hours.
> added christmas support hours

- src/components/Common/Footer.tsx
- src/translation/extractedMessages.json
> copyright update

- src/styles/_inputs.scss
> adapted switch label to multipel rows of text

- src/components/Help.tsx
> Commented out holiday hours for later use

- src/components/Common/UserNameInput.tsx
- src/components/Login/UsernamePw.tsx
- src/helperFunctions/validation/regexPatterns.ts
- src/helperFunctions/validation/validateUserName.ts
- src/tests/login/LoginMain-test.tsx
- src/tests/login/LoginResetPassword-test.tsx
- src/translation/extractedMessages.json
> Add validation for login using email address and eppn as username

- src/components/Common/Header.tsx
- src/components/Login/LoginMain.tsx
> display logout button on error

- .vscode/settings.json
- src/components/Common/PageNotFound.tsx
- src/components/Dashboard/DashboardMain.tsx
- src/components/HelpMain.tsx
- src/components/Login/LoginApp.tsx
- src/components/ResetPassword/ResetPasswordMain.tsx
- src/components/Signup/SignupMain.tsx
- src/components/SwamidErrors/ErrorsMain.tsx
- src/translation/extractedMessages.json
> Add page not found component

- .vscode/settings.json
- src/components/Common/Security.tsx
- src/components/Help.tsx
- src/styles/_Help.scss
- src/styles/_Security.scss
- src/styles/_typography.scss
- src/translation/extractedMessages.json
Added nested accordion with specific security key info in FAQ, and link to FAQ from Advanced settings.
> Cat faq securitykeys

- src/components/Dashboard/VerifyIdentity.tsx
- src/components/Help.tsx
- src/tests/BankID-test.tsx
- src/tests/VerifyIdentity-test.tsx
- src/translation/extractedMessages.json
Updated Freja Faq and title on Swedish verification
> Cat freja samordnings

- src/components/Dashboard/VerifyIdentity.tsx
- src/tests/Svipe-test.tsx
- src/translation/extractedMessages.json
Added disable on panel and button, copy for non available option.
> disabling svipe option, added copy

- src/components/Help.tsx
- src/translation/extractedMessages.json
Referencing key list in faq section
> Cat faq keylist text

- src/apis/eduidSignup.ts
- src/commonConfig.ts
- src/components/Signup/SignupApp.tsx
- src/tests/helperFunctions/SignupTestApp-rtl.tsx
- src/tests/signup/SignupMain-test.tsx
> Use the config.signup_service_url instead of a hardcoded variable url

- src/commonConfig.ts
- src/components/Common/GenericError.tsx
- src/components/Common/Header.tsx
- src/components/Common/PageNotFound.tsx
- src/components/ResetPassword/SetNewPassword.tsx
> fix issue, logout does not redirect to the eduid home page

- src/translation/defaultMessages/common.tsx
- src/translation/extractedMessages.json
> Eunju add pdata.display name invalid

- src/components/Common/PersonalDataForm.tsx
- src/components/Dashboard/PersonalDataParent.tsx
- src/styles/_PersonalData.scss
- src/styles/_base.scss
- src/styles/_buttons.scss
- src/styles/_forms.scss
- src/styles/_reactSelect.scss
- src/translation/defaultMessages/common.tsx
- src/translation/extractedMessages.json
> Display name selection feature for verified users

- src/components/Signup/SignupApp.tsx
- src/translation/extractedMessages.json
> Add document title register

- src/components/Help.tsx
- src/styles/_typography.scss
- src/translation/extractedMessages.json
Temp red text saying what and why under vefification and Svipe details.
> Svipe unavailable text in faq

- src/components/Common/CopyToClipboard.tsx
- src/components/ResetPassword/SetNewPassword.tsx
Created a component for reuse in multiple places
> Create CopyToClipboard component

- src/components/Dashboard/Emails.tsx
> Remove placeholder and helpblock

- src/components/Dashboard/Emails.tsx
- src/helperFunctions/validation/regexPatterns.ts
Long + short with slight modifications, to be replaced by just short after next release.
> temp combo email regex

- src/styles/_PersonalData.scss
- src/styles/_reactSelect.scss
Matched disabled colours to variables for rest of site,
increased cell with for personal settings to break more nicely.
> Cat disabled displayname

- src/components/ResetPassword/EmailLinkSent.tsx
- src/translation/extractedMessages.json
> Eunju textedit code

- src/styles/_reactSelect.scss
> stubborn disabled low-contrast text fix

- src/components/Login/UseOtherDevice1.tsx
> Fix, continue button clicks not occurring (login other device)

- src/styles/_Faq.scss
> hiding key update in faq

- src/components/ResetPassword/ResetPasswordApp.tsx
> Resolved issue with invisible SelectedSecurityToken view

- src/components/Login/UseOtherDevice2.tsx
> fix duplicated fetchUseOtherDevice2 requests

- src/components/ResetPassword/ResetPasswordApp.tsx
- src/translation/defaultMessages/resetPassword.tsx
- src/translation/extractedMessages.json
> Eunju fix empty phone code sent

- src/components/IndexMain.tsx
> Redirect to /profile/ when the url is /profile

- src/components/Dashboard/AccountId.tsx
Updated Eppn heading and copy to Unique ID etc to avoid confusion.
> Eppn copy edit

- src/components/Dashboard/Emails.tsx
- src/helperFunctions/validation/regexPatterns.ts
No more long email codes will be sent out so we need only validate short versions.
> removed combo regex

- src/components/Dashboard/Emails.tsx
- src/translation/extractedMessages.json
> Eunju placeholder emailcode

- src/components/ResetPassword/EmailLinkSent.tsx
- src/components/ResetPassword/HandleExtraSecurities.tsx
- src/components/ResetPassword/PhoneCodeSent.tsx
- src/components/ResetPassword/ResetPasswordApp.tsx
- src/components/ResetPassword/ResetPasswordEnterEmail.tsx
- src/components/ResetPassword/SelectedSecurityToken.tsx
- src/components/ResetPassword/SetNewPassword.tsx
- src/tests/login/LoginResetPassword-test.tsx
> Reset Password: update heading text

- src/components/Common/NewPasswordForm.tsx
- src/components/ResetPassword/SetNewPassword.tsx
- src/components/Signup/SignupUserCreated.tsx
- src/styles/_ResetPassword.scss
- src/styles/_inputs.scss
> Make the password manager pop up on the confirm user info page

- src/components/Signup/SignupCaptcha.tsx
- src/components/Signup/SignupEmailForm.tsx
- src/components/Signup/SignupEnterCode.tsx
- src/components/Signup/SignupToU.tsx
- src/components/Signup/SignupUserCreated.tsx
- src/tests/signup/SignupMain-test.tsx
> Register: clarify heading

- src/styles/_Header.scss
Same padding as buttons, same color as icon
> user-nav-button-lookalike

- src/components/Help.tsx
> dont include personal number bold

- src/apis/eduidSignup.ts
- src/components/Common/EmailInput.tsx
- src/components/Common/InputWrapper.tsx
- src/components/Signup/SignupEmailForm.tsx
- src/helperFunctions/validation/validateEmail.ts
- src/slices/Signup.ts
- src/tests/signup/SignupMain-test.tsx
> Require users to register names at signup 

- src/components/ResetPassword/SetNewPassword.tsx
- src/components/Signup/SignupUserCreated.tsx
> Remove input name, to fix the issue of new passwords appearing in the url

- src/components/Signup/SignupEmailForm.tsx
> Eunju add formsubmit

- src/translation/defaultMessages/eidas.tsx
> Add missing messages

- src/components/Dashboard/AdvancedSettings.tsx
> Eunju remove unique id advanced settings

- src/components/Help.tsx
- src/translation/extractedMessages.json
> Eunju add support phone

- src/components/Login/LoginExternalReturnHandler.tsx
- src/components/ResetPassword/ResetPasswordApp.tsx
> Fix the issue of not continuing after coming back from an external page

- src/components/Dashboard/DeleteAccount.tsx
- src/translation/extractedMessages.json
> Update modal text for deleting account

- src/styles/_tables.scss
> Add grid for phone-display

- src/components/Dashboard/UseSecurityKeyToggle.tsx
> add help-text to 2FA toggle and hacked in styling

- src/components/Common/NewPasswordForm.tsx
- src/components/Dashboard/ChangePassword.tsx
- src/components/Dashboard/ChangePasswordCustom.tsx
- src/components/Dashboard/ChangePasswordSuccess.tsx
- src/components/ResetPassword/SetNewPassword.tsx
- src/components/Signup/SignupUserCreated.tsx
- src/slices/ResetPassword.ts
> Eunju custom password resetpw

- src/components/Common/NewPasswordForm.tsx
- src/components/ResetPassword/SetNewPassword.tsx
- src/components/Signup/SignupUserCreated.tsx
- src/translation/extractedMessages.json
> Release feedack fixes

- src/components/Common/Security.tsx
- src/components/Dashboard/Authenticate.tsx
- src/components/Dashboard/ChangePassword.tsx
- src/components/Dashboard/ChangePasswordDisplay.tsx
- src/components/Dashboard/DeleteAccount.tsx
- src/components/Dashboard/UseSecurityKeyToggle.tsx
- src/components/Dashboard/VerifyIdentity.tsx
> Summer features fixes

- src/components/Common/CommonToU.tsx
- src/components/Common/ResponseCodeAbortButton.tsx
- src/components/Dashboard/Emails.tsx
- src/components/Login/LoginAbortButton.tsx
- src/components/Login/UseOtherDevice1.tsx
- src/components/Login/UseOtherDevice2.tsx
- src/components/ResetPassword/SetNewPassword.tsx
- src/components/Signup/SignupCaptchaForm.tsx
- src/components/Signup/SignupCredentials.tsx
- src/components/Signup/SignupUserCreated.tsx
- src/translation/extractedMessages.json
> Eunju unify translated text

- src/components/Dashboard/UseSecurityKeyToggle.tsx
- src/styles/_forms.scss
> added scss class legend-2fa to style the notes under the 2FA toggle

- package-lock.json
- src/components/Common/PasswordStrengthMeter.tsx
- src/components/Common/PersonalDataForm.tsx
- src/components/Common/Security.tsx
- src/components/Dashboard/ChangePassword.tsx
- src/components/Dashboard/Phones.tsx
- src/components/ResetPassword/SetNewPassword.tsx
- src/components/Signup/SignupEmailForm.tsx
- src/components/Signup/SignupUserCreated.tsx
- src/styles/_ChangePassword.scss
- src/tests/signup/SignupMain-test.tsx
- src/translation/extractedMessages.json
1. fixed custom password Save button not working in signup
2. placeholder text changed to lowercase
3. strong password text color changed to green 
4. unified separate decryption texts into one
> Frontend minor issues

- src/components/Help.tsx
- src/translation/extractedMessages.json
> support hours update

- src/components/Dashboard/VerifyIdentity.tsx
- src/styles/_figure.scss
> Add remove button for eidas so users can remove their identity

- src/apis/eduidFrejaeID.ts
- src/apis/eduidPersonalData.ts
- src/commonConfig.ts
- src/components/Common/ExternalReturnHandler.tsx
- src/components/Dashboard/DashboardStart.tsx
- src/components/Dashboard/Recommendations.tsx
- src/components/Dashboard/VerifyIdentity.tsx
- src/components/Help.tsx
- src/styles/_figure.scss
- src/tests/FrejaeID-test.tsx
- src/translation/extractedMessages.json
> Implement Freja eID instead of Svipe verification

- src/components/Help.tsx
- src/translation/extractedMessages.json
> Cat faq update post release

- src/styles/_modals.scss
Responsive modal width, slightly narrower than content.
> reusing content width for responsive modal width

- src/apis/eduidAuthn.ts
- src/components/Common/Security.tsx
- src/components/Dashboard/Authenticate.tsx
- src/components/Dashboard/UseSecurityKeyToggle.tsx
- src/components/Dashboard/VerifyIdentity.tsx
- src/components/Index.tsx
- src/slices/Authn.ts
- src/slices/Security.ts
when the user needs to log in again(security zone), once they complete the login and return, the action they were attempting before will be automatically triggered.
> remove extra button click

- src/components/Common/Footer.tsx
- src/components/Common/Security.tsx
- src/components/Dashboard/ChangePassword.tsx
- src/components/Help.tsx
- src/components/IndexMain.tsx
- src/components/ResetPassword/ResetPasswordApp.tsx
- src/translation/extractedMessages.json
> change path faq -> help, edit title

- src/styles/_modals.scss
> increase the top margin of the modal footer css

- src/components/Login/SecurityKey.tsx
> Fix bug where authentication only performs the first time

- src/components/Login/SecurityKey.tsx
> Trigger MfaAuthn when the user clicks the button

- package-lock.json
- src/translation/extractedMessages.json
> Audit fix and make translation

- src/components/Common/Security.tsx
- src/styles/_forms.scss
- src/translation/extractedMessages.json
> Device disabled help text

- src/components/Signup/SignupApp.tsx
- src/components/Signup/SignupEnterCode.tsx
- src/components/Signup/SignupToU.tsx
- src/machines/SignupMachine.ts
upon reloading the page in the signup flow, the user started at the first step, but the user should remain at the correct progress when the frontend knows which step they need to complete.
> Eunju singup state

- src/apis/common.ts
- src/ts_common.ts
> Handle 401 error by triggering autehntication request

- src/apis/eduidLogin.ts
- src/components/Common/Header.tsx
- src/components/Login/Login.tsx
- src/components/Login/TemporaryInfo.tsx
- src/styles/_Help.scss
- src/styles/_buttons.scss
- src/styles/_figure.scss
- src/styles/_forms.scss
- only visible to users who have verified using the phone verification method
> info page for discontinuing mobile phone number

- src/components/Common/PersonalDataForm.tsx
> fix issue when user click edit does nothing but request wrong data

- src/components/Dashboard/DataTable.tsx
- src/components/Dashboard/Recommendations.tsx
> Eunju styling confirm

- src/apis/common.ts
- src/components/Login/LoginExternalReturnHandler.tsx
> Trigger RequestAllUserData when status.frontend_action === login

- src/components/Dashboard/VerifyIdentity.tsx
- src/translation/extractedMessages.json
> Remove /by post

- src/components/SwamidErrors/Errors.tsx
> Remove duplicated class

- src/components/Common/NewPasswordForm.tsx
> Add unique id for cancel button

- src/components/Login/TemporaryInfo.tsx
- src/styles/_figure.scss
- src/translation/extractedMessages.json
> Eunju adjust infotext

- src/components/Common/Security.tsx
- src/tests/Security-test.tsx
- src/translation/extractedMessages.json
changed text describing the action adding a new security key, changed security key button text
> changed text describing the action adding a new security key, changed security key button text

- src/components/IndexMain.tsx
- Dashboard:  AuthenticateModal element visible 
--------
- Landing page: AuthenticateModal element not visible
> Move the authenticateModal component to responds only in the dashboard

- src/components/Common/SwedishEID.tsx
> Remove the fieldset to fix issues the missing legend

- src/components/Dashboard/DataTable.tsx
> Fix issue, make the primary button active for emails

- src/components/Login/Login.tsx
- src/components/Login/MultiFactorAuth.tsx
- src/components/ResetPassword/HandleExtraSecurities.tsx
- src/translation/extractedMessages.json
> Remove bankID, Freja option is available for unverified account and show only remember me toggle on the password page

- src/components/Help.tsx
> Correct signup link

- src/components/Dashboard/PersonalDataParent.tsx
- src/translation/extractedMessages.json
> updated title of the name edit box

- src/components/Dashboard/Account.tsx
- src/components/Dashboard/AccountId.tsx
- src/components/Dashboard/DashboardStart.tsx
- src/components/Dashboard/Recommendations.tsx
- src/components/Help.tsx
- src/styles/_DashboardMain.scss
- src/styles/_Header.scss
- src/styles/_forms.scss
- src/tests/DashboardMain-test.tsx
- src/translation/extractedMessages.json
> Cat overview adaptations

- src/components/Dashboard/Identity.tsx
- src/components/Help.tsx
- src/translation/extractedMessages.json
> translations

- src/components/Common/MultiFactorAuthentication.tsx
- src/styles/_figure.scss
- src/styles/_tables.scss
- src/tests/Security-test.tsx
> changed the table style to figure style for security keys

- src/components/Common/Footer.tsx
- src/components/Common/MultiFactorAuthentication.tsx
- src/components/Common/PersonalDataForm.tsx
- src/components/Dashboard/Recommendations.tsx
- src/components/Help.tsx
- src/translation/extractedMessages.json
Open help links in new tab
Copy edits displayname and start overview
Start overview account consistent info
Help assurance level copy edits
> Cat translations

- src/components/Signup/SignupApp.tsx
> Request fetchLogout when user is already signed up

- src/components/Common/Header.tsx
- src/tests/login/LoginMain-test.tsx
> Update, login button will not be present on the help and index pages

- src/components/Dashboard/Emails.tsx
- src/translation/extractedMessages.json
> Update modal text

- src/components/Common/CommonToU.tsx
- src/components/Help.tsx
- src/tests/signup/SignupMain-test.tsx
- src/translation/extractedMessages.json
Displaying terms of use (reuse from signup) i help section
> Cat tou help

- src/styles/_buttons.scss
> making login nr 1 in responsive login form

- src/components/Help.tsx
> Add variable for locale-specific link

- src/components/Help.tsx
- src/styles/_Help.scss
- src/translation/extractedMessages.json
Help edits:
- Reference to assurance levels and DNP 
- Detailed how to register eduID numbered list
- added Sunet website language comment
- Language specific and translated links to Antagning, Freja and BankID.
> Cat help instructions update

- src/components/Dashboard/Language.tsx
> Fix the issue, cannot change language option

- src/components/Common/EmailInUse.tsx
- src/components/Common/HeaderNav.tsx
- src/components/Common/MultiFactorAuthentication.tsx
- src/components/Common/NinDisplay.tsx
- src/components/Dashboard/AccountLinking.tsx
- src/components/Dashboard/ChangePasswordDisplay.tsx
- src/components/Dashboard/ChangePasswordSuccess.tsx
- src/components/Dashboard/DeleteAccount.tsx
- src/components/Dashboard/Emails.tsx
- src/components/Dashboard/Identity.tsx
- src/components/Dashboard/Ladok.tsx
- src/components/Dashboard/Language.tsx
- src/components/Dashboard/NinForm.tsx
- src/components/Dashboard/Phones.tsx
- src/components/Dashboard/UseSecurityKeyToggle.tsx
- src/components/Login/NewDevice.tsx
- src/components/ResetPassword/EmailLinkSent.tsx
- src/components/ResetPassword/SetNewPassword.tsx
- src/components/Signup/SignupUserCreated.tsx
- src/styles/_Emails.scss
- src/styles/_Nins.scss
- src/styles/_tables.scss
- Removed the id and added a class name instead.
- the  Fieldset should be inside the form
- Removed unneccary Fieldset
> unify html structure

- src/components/Help.tsx
- src/styles/_lists.scss
- src/translation/extractedMessages.json
Nested list explaining start page content in Use - Update settings help secion.
> Cat usingedu id help edits

- src/components/Help.tsx
> grammar tweaks etc

- src/translation/extractedMessages.json
> translation

- src/components/Dashboard/Security.tsx
- src/components/Help.tsx
- src/translation/extractedMessages.json
> Cat help identitypage

- src/components/Login/Login.tsx
> Remove the temporary information about removing phone verification

- src/apis/eduidSignup.ts
- src/components/Signup/SignupEnterCode.tsx
- src/tests/signup/SignupMain-test.tsx
- src/translation/extractedMessages.json
> Replace send a new code link when the code expires

- src/components/Common/Captcha.tsx
> Reset form after successful form submission

- src/components/Help.tsx
- src/styles/_Help.scss
- src/translation/extractedMessages.json
Help content on account > orcid, esi, delete, change pw,
list styling,
some security key wording edits, 
updated references in help to Settings / Advanced Settings.
> Cat help account

- src/components/Common/MultiFactorAuthentication.tsx
- src/components/Dashboard/AuthenticateModal.tsx
- src/translation/extractedMessages.json
> Inform the user what will happen after logging in

- src/components/ResetPassword/ResetPasswordApp.tsx
- src/components/ResetPassword/ResetPasswordCaptcha.tsx
- src/components/ResetPassword/ResetPasswordEnterEmail.tsx
- src/machines/ResetPasswordMachine.ts
- src/machines/ResetPasswordMachine.typegen.ts
- src/tests/login/LoginResetPassword-test.tsx
- src/translation/defaultMessages/resetPassword.tsx
- src/translation/extractedMessages.json
> make the user enter the email address before completing the captcha

- src/components/Signup/SignupEmailForm.tsx
- src/components/Signup/SignupEnterCode.tsx
- src/translation/extractedMessages.json
Informing to use useful address,
sender address,
that protected identities should use Freja
and that they always need to visit ATG.
> Cat emailadress info

- src/components/Help.tsx
- src/translation/extractedMessages.json
More correct punctuation in list for help sections Create and Use.
Translation help fixes regarding protected id.
> Cat help list capitalization

- src/components/Help.tsx
- src/translation/extractedMessages.json
Added textual SWAMID assurance levels to help section.
> Cat help swamid terms

- src/components/Dashboard/BankID.tsx
- src/components/Dashboard/Eidas.tsx
- src/components/Dashboard/Identity.tsx
- src/components/Help.tsx
- src/tests/Eidas-test.tsx
- src/tests/VerifyIdentity-test.tsx
- src/translation/extractedMessages.json
Removing inaccurate id-card references.
> removing "card" from digital IDs, translation.

- package-lock.json
- src/components/Common/MultiFactorAuthentication.tsx
- src/components/Common/NotificationModal.tsx
- src/components/Dashboard/AuthenticateModal.tsx
- src/components/Dashboard/Recommendations.tsx
- src/styles/_base.scss
- src/styles/_figure.scss
- src/styles/_typography.scss
- src/translation/extractedMessages.json
- Added note text in security check modals.
- Added a link to the verify security key section from the start page.
- Changed focus when the user adds a security key, so the user can check the added security keys in table
> update security page usability

- src/components/Common/MultiFactorAuthentication.tsx
- src/components/Dashboard/AuthenticateModal.tsx
- src/translation/defaultMessages/common.tsx
- src/translation/extractedMessages.json
Update the error message for errors in the form
> Fix the issue of requesting an empty frontend action to the backend when logging in with Freja.

- src/components/Common/MultiFactorAuthentication.tsx
> Change the focus to the security key table when user removes or verifies the security key successfully

- src/components/Dashboard/Recommendations.tsx
- src/styles/_DashboardMain.scss
Start page status overview, checkmark on completed steps, and pale gray "!" on not completed.
> exlamation inst of empty circle, gray.

- src/components/Index.tsx
- src/translation/extractedMessages.json
> Eunju separate two text

- src/components/Index.tsx
- src/translation/extractedMessages.json
> Eunju separate link text

- src/components/Index.tsx
- src/styles/_landingPage.scss
- src/translation/extractedMessages.json
Remove the lead div to eliminate the bottom border and  How it works: text
> Eunju fix landing page

- src/components/Common/SecurityKey.tsx
- src/components/Index.tsx
- src/styles/_inputs.scss
- src/styles/_landingPage.scss
- src/translation/extractedMessages.json
- src/translation/languages/en.json
- src/translation/languages/sv.json
> Add focus to the login mfa button so the user can easily click or press Enter on it

- src/components/Dashboard/Account.tsx
- src/components/Dashboard/Identity.tsx
- src/components/Dashboard/Security.tsx
- src/translation/extractedMessages.json
Removing continue/back to always feel accurate in case of direct navigation...
> Technically correct copy

- src/components/ResetPassword/HandleExtraSecurities.tsx
> Fix link style

- src/components/Common/CommonToU.tsx
- src/components/Common/HeaderNav.tsx
- src/components/Dashboard/DeleteAccount.tsx
- src/components/Help.tsx
- src/translation/extractedMessages.json
Informing user of re-acceptance of terms if terms change and adding terms "spärra/block" to interface in places where deletion of account is mentioned.
> Cat revision copy

- src/components/Common/CommonToU.tsx
- src/components/Help.tsx
- src/translation/extractedMessages.json
Legal blurb went missing and found.
> Re-adding help sentence that fell out

- src/components/Common/Notifications.tsx
> Bye, alert reactstrap

- src/components/Common/ConfirmModal.tsx
- src/components/Common/MultiFactorAuthentication.tsx
- src/components/Common/NotificationModal.tsx
- src/styles/_DashboardMain.scss
- src/styles/_modals.scss
> Bye modal reactstrap

- src/components/Common/CustomInput.tsx
- src/components/Common/EduIDTextInput.tsx
- src/components/Common/InputWrapper.tsx
- src/components/Common/PasswordInput.tsx
- src/components/Common/PasswordStrengthMeter.tsx
- src/styles/_inputs.scss
> Bye input reactstrap

- src/tests/DashboardStart-test.tsx
- src/tests/DeleteAccount-test.tsx
- src/tests/Security-test.tsx
- src/tests/VerifyIdentity-test.tsx
> Add more unit tests

- src/tests/DeleteAccount-test.tsx
wait until api event has been called
> wait for api event to go through

- src/components/Common/PasswordInput.tsx
- src/components/Login/LoginAbortButton.tsx
- src/components/Login/UsernamePw.tsx
> Submit the login form with the Enter key when the password input is filled and focused

- src/components/Common/Captcha.tsx
- src/components/Common/EduIDButton.tsx
- src/components/Common/NewPasswordForm.tsx
- src/components/Common/PersonalDataForm.tsx
- src/components/ResetPassword/EmailForm.tsx
To make the Enter key work correctly, the submit button must be type='submit', and all other buttons should have a type as well.
> Ensure correct button types for proper Enter key behavior

- src/components/Login/ResponseCodeForm.tsx
- src/styles/_inputs.scss
- Contrast issue between the background and text in the copy/paste input and the copy/paste toggle button.
- Slightly lightened the input background color. 
- Add aria-label to ensure every form element has a label.
> Fix web accessibility issues

- src/components/Common/HeaderNav.tsx
- src/components/Dashboard/DashboardBreadcrumbs.tsx
- src/components/Dashboard/Identity.tsx
> Resolve the web accessibility warnings

- src/components/Common/AccordionItemTemplate.tsx
- src/components/Common/Captcha.tsx
- src/components/Common/CommonToU.tsx
- src/components/Common/GenericError.tsx
- src/components/Common/InputWrapper.tsx
- src/components/Common/SecurityKey.tsx
- src/components/Common/ShowAfterDelay.tsx
- src/components/Dashboard/ChangePasswordDisplay.tsx
- src/components/Dashboard/DashboardBreadcrumbs.tsx
- src/components/Login/TemporaryInfo.tsx
- src/styles/_forms.scss
- src/styles/_tables.scss
- src/styles/_typography.scss
> Add readonly and cleanup

- src/apis/eduidBankid.ts
- src/apis/eduidEidas.ts
- src/apis/eduidFrejaeID.ts
- src/components/Common/MultiFactorAuthentication.tsx
- src/translation/extractedMessages.json
> Implement security key verification support for Eidas and refactor verification logic

- src/styles/_Header.scss
- src/styles/_Notifications.scss
- src/styles/_accordion.scss
- src/styles/_buttons.scss
- src/styles/_figure.scss
- src/styles/_forms.scss
- src/styles/_inputs.scss
- src/styles/_lists.scss
- src/styles/_reactSelect.scss
- src/styles/_tables.scss
- src/styles/_typography.scss
-removed unnecessary font-weight declarations
-changed declarations from numerical to text to simplify (700=>bold/500=>normal etc) for Akkurat
-changed bolded Inter font text to use class .text-bold which implements semi-bold font variant and normal font-weight for crisp result.
> Cat bold text font refactor

- package-lock.json
- package.json
- src/components/IndexMain.tsx
- src/components/ScrollToHash.tsx
- src/modules.d.ts
> Remove scroll to hash dependency and use own scroll handler

- src/components/Common/Captcha.tsx
- src/components/Common/PersonalDataForm.tsx
- src/components/Dashboard/Ladok.tsx
- src/styles/_PersonalData.scss
- src/styles/_buttons.scss
- src/styles/_figure.scss
Updated refresh button and captcha alt and invalid label,
span inst of invalid ladok label,
text link invalid styles,
remove/reuse of css,
centering in figure.
> Cat no invalid labels

- src/components/Common/PersonalDataForm.tsx
- src/components/Dashboard/Language.tsx
- src/styles/_reactSelect.scss
> UI cleanup when display name is disabled

- src/components/Dashboard/UseSecurityKeyToggle.tsx
> clarify that only security key is used, not full 2FA

- src/components/Common/SwedishEID.tsx
- src/styles/_Login.scss
- src/translation/extractedMessages.json
Help text under mfa login options
> centering and specifying mfa help text

- src/apis/eduidLogin.ts
- src/components/Login/MultiFactorAuth.tsx
> use state swedish eid instead of freja eid to activate recovery button

- src/components/Dashboard/PersonalDataParent.tsx
- src/tests/VerifyIdentity-test.tsx
- src/translation/extractedMessages.json
> Change  the X button to a Close and position it in the same place as the edit button

- src/components/Login/Login.tsx
Letting 'em know more exactly how to get out of the terminated user page.
> Clarified help text for Terminators

- src/components/Dashboard/Language.tsx
addendum to pr #2125
only try to set language when app is loaded
> only try to save language when app is loaded

- src/components/Help.tsx
- src/translation/extractedMessages.json
Blurb about available modes based on system setting, default and toggle override.
> added color mode info in help Accessibility section

- src/components/Common/MultiFactorAuthentication.tsx
- src/translation/extractedMessages.json
Just a little bit more descriptive reference to security keys in security page.
> Cat security key text

- src/components/Common/MultiFactorAuthentication.tsx
- src/components/Dashboard/UseSecurityKeyToggle.tsx
- src/styles/_modals.scss
- src/translation/extractedMessages.json
Added "Not now" link in MFA dialog, edited the helptext above.
Simplified copy in Always use security key toggle.
> Cat verify sk modal

- src/apis/eduidSecurity.ts
- src/components/Common/MultiFactorAuthentication.tsx
This PR fixes the registration of new keys. There was a mismatch on data shapes in the communication with the backend
> fix communication with backend for registration of new keys

- src/components/Common/MultiFactorAuthentication.tsx
Fix logic in check when removing security key. If a new login is required the key should be removed after login as previously
> Fix removal of security key

- src/components/Common/SecurityKey.tsx
Make sure to clear notifications only on success else the notification error is never shown when cancelling usage of your key
> Clear notifications on success only

- src/apis/navigatorCredentials.ts
With extensions that overload browser methods and classes we seem to get other errors than DOMEXceptions so extract message for display for all errors
> Extract message from more errors
