SUNET/eduid-front

src/style/Nins.scss, src/style/base.scss
Summary: 
- **base.scss**: changes .btn-group-vertical from `display: flex-inline` to `display: block`
- **base.scss**: removes uppercase from helper text under buttons
- **nins.scss**: comments out some redundant media queries
=> fixes formatting of nin buttons

src/components/DashboardMain.js, src/components/Nins.js, src/components/VerifyIdentity.js, src/style/DashboardMain.scss, src/style/Nins.scss, src/style/base.scss, src/tests/Nins-test.js
Summary: 
- splits out parts of the original nin component into smaller functions, to allow them to be rendered in new ways (new renders: `ninForm`, `ninNumber`, `VerifyButton`, `RemoveButton`, `NinButtons`)
- splits out the specific elements to be rendered depending on `ninStatus` have been gathered in variables (noNin, ninUnverified, ninVerified)
- adds another condition (in addition to `ninStatus` 🤦‍♀ ) to only render certain functions at specific URLs (**Step 1. add nin/display saved nin** rendered at `/verify-identity/step1` and  **Step 2. display vettingButtons** rendered at `/verify-identity/step2`)
- adds some styling to get an idea of where it's headed (NOT FINAL!)
⚠️Warning!
- I have commented out the **Nin component** and **Nin container** test to make Travis happy. Will make …
=> A first non-elegant refactor of the nin component

plugins/eduid_action.mfa/component.js
prevent calling credentials.navigator.get twice
=> prevent calling navigator.get twice

plugins/eduid_action.mfa/component.js, src/components/AddNin.js, src/components/NinForm.js, src/components/Nins.js, src/sagas/LookupMobileProofing.js
**Background:** In prod nin is sent to db on click of the vetting buttons. In semi-new version users should feel like nin is added in a separate step before they are presented with the vetting buttons.    
Work summary: 
- Adds new component AddNin.js (child of Nins.js)
- Adds new component NinForm (child of AddNin.js)
- NinForm collects nin, validates it and, if nin passes validation, renders an ADD button
- The ADD button passes the valid nin back to parent (AddNin)
- AddNin is responsible for rendering the NinForm if a valid nin has been passed form NinForm
Next steps: 
- Refactoring dashboard (pt2): Add new component DisplayNin (child of AddNin.js) that renders different info and styles depending on verification status of the number
- Refactoring dashboard (pt3): Using existing logic …
=> Refactoring dashboard (pt1): Holding on to nin as a separate step

src/actions/Nins.js, src/components/AddNin.js, src/components/NinDisplay.js, src/components/NinForm.js, src/components/Nins.js, src/dashboard-root-saga.js, src/sagas/Nins.js, src/style/Nins.scss
**Background**:  The dashboard is being reengineered to make users aware that adding their nin is the first step in a 2-step process to complete their eduid.
What it should do: 
- ADD button under the input should only render when a user types a valid nin (otherwise should trigger the existing error messages about invalid input)
- ADD button onClick  > dispatch postNin() > POST_NIN action > postNin() saga (nin to backend and populated nin array returned) > both FAIL and SUCCESS responses should be handled 
- The render logic is dependent on the nin array being populated and its verification status
- Notifications have also been added to the dashboard to show feedback
- All changes to local state should have been removed
> Please let me know if you spot any bugs 🔍
What it does not do: 
- …
=> Adds postNin saga to new endpoint

i18n/src/i18n-messages.json, src/actions/LookupMobileProofing.js, src/components/AddNin.js, src/components/GenericConfirmModal.js, src/components/LookupMobileProofing.js, src/components/NinDisplay.js, src/containers/LookupMobileProofing.js, src/i18n-messages.js, src/reducers/LookupMobileProofing.js, src/sagas/LookupMobileProofing.js, src/style/base.scss, src/tests/LookupMobileProofing-test.js
**Background**: We need to inform users that for phone vetting we need a number in addition to their nin and where to go to add and confirm their number. The two other vetting options trigger modals, so one has been added to phone vetting.
**Summary**: 
- the vetting buttons are only visible after a valid nin has been added to user
- clicking the phone vetting button opens a modal with different info depending on whether or not the user has at least one phone number
-  (no number): Modal informs the user to go to Settings to add and confirm the number
- (added number, but not confirmed): Modal informs the user to go to Settings to confirm the number
- (added and confirmed number): Modal informs the user what the vetting check will do and asks user to trigger the check
- all modals have …
=> Adds modal guiding user through phone vetting (simplest solution)

src/tests/ChangePasswordForm-test.js, src/tests/NinForm-test.js
*Background:* Although testing of form input will be done manually, these tests ensure expected render of the most crucial elements of the components with a form 
*Summary:*
- NinForm: renders input (for nin) and button (to add nin to user)
- ChangePasswordForm: renders inputs (for old/new passwords) and button (for saving new password)
=> Rendering tests for components with forms

src/components/Orcid.js
Background: For added ORCID accounts the remove button renders a string with an unknown id (tl.remove) instead of the intended text.
Summary: 
-  I have replaced the text with the svg symbol used elsewhere in the app for removing data
=> Fix remove button for ORCID account

i18n/src/i18n-messages.json, src/components/Email.js, src/components/Footer.js, src/i18n-messages.js, src/style/Footer.scss, src/style/Header.scss, src/style/SignupMain.scss, src/style/base.scss
**Background**: This is an update to the footer in sign up to remove info links. 
**Summary**: 
- I have removed the 4 info links
- I have renamed FAQ to Help (as per Home and Login)
- I have made the margin consistent with Home and Login (1rem/16px)
- I have also made the email input fill the entire page up to the REGISTER button
- I have cleaned out some commented out code from the component
---
> ⚠️ Ideally, **Signup** and **Login** would both have translation options in the footer. But because Login only exists in English I have chosen what is currently in use (i.e. Signup and Login only in Eng) until they are both translated.
---
**Next step**: 
- I would also like to make the white banner in the header consistent with the Login (not as high white background, make the white part only …
=> Updates sign in footer in line with homepage and login 

src/components/NinForm.js
Background: The input accepting national identity numbers has the following bugs:
1. Adds incorrect nin values to the URL if user presses Enter
2. Results in the following console.error after stalling and not saving the number when user clicks the ADD button 
Summary: 
- Moved `<button>` inside the `<Form>` component
- Added `e.preventDefault()` to the `onSubmit` event of the `<Form>` component 
- Added more robust DOM traversal to read the nin `<input>` value
=> NIN input fix: values in the URL and console.error

i18n/l10n/sv.json, plugins/eduid_action.mfa/test.js, src/components/Footer.js, src/containers/Footer.js, src/style/Footer.scss, src/tests/Footer-test.js
**Background**: Footers across the website are inconsistent. This is a proposal of a standard way to fit all of the current info (see screenshot).
**Summary**: 
- I have removed the information links (from component and the container), excluding the 'FAQ' which is now renamed to 'Help'
- I have hidden the non-selected language with css, so that only the clickable option is visible (i.e. it shows the language you are not using so you can switch to it)
- I have refactored the component and the css (media queries not needed anymore)
**Next steps**: 
- As a standard footer this is what we should aim for all pages to look in the long term
- Pages that differ are: 
- TOU for existing users (outdated - needs updating)
- Home (currently does not have copyright - needs updating)   
- Login/Signup …
=> Fix to update Footers across website

src/components/ActionWrapper.js, src/components/DashboardMain.js, src/components/Header.js, src/components/HeaderAnon.js, src/components/SignupMain.js, src/containers/Header.js, src/containers/HeaderAnon.js, src/tests/Header-test.js
**Background**:  The updated app requires a more flexible header. 
- Outside of the app, buttons need to navigate to signup or login 
- Inside the app, a button needs to log users out
- Some pages (TOU for existing users or reset password) should not have any button
**Summary**: 
- I have refactored the `<Header />` component to display different buttons based on URL (location.pathname)
- I have moved the code and proptypes from `<HeaderAnon />` to `<Header />` (component and container)
- I have commented out the code in `<HeaderAnon />` (component and container)
- I have removed all imports of `<HeaderAnon />`
-  I have also updated the test in line with these changes
=> Refactor Header to allow different styles across website

i18n/l10n/sv.json, i18n/src/i18n-messages.json, plugins/eduid_action.tou/ToU-test.js, plugins/eduid_action.tou/component.js, src/components/ActionWrapper.js, src/components/DashboardMain.js, src/components/Header.js, src/components/HeaderAnon.js, src/components/SignupMain.js, src/containers/Header.js, src/containers/HeaderAnon.js, src/i18n-messages.js, src/style/DashboardMain.scss, src/tests/Header-test.js
**Background**: The TOU that existing users have to accept after signup has been updated.
**Summary**: 
- Footer is updated (uses the same as dashboard, so addressed in PR #98)
- Header is updated (uses the Header without button, addressed in PR #99, and the banner from the home page with one sentence tagline and the narrower white box)
- I have updated the react code with the one-line tagline from the home page (Eng and Swe translations)  
- I have removed the cancel button (because it only triggered text saying that you had to click accept) 
- I have updated the test as per these changes 
**Next step**:
- Update the rest of the app with the narrower one line banner
=> Styling fix for TOU (for exiting users) 

src/style/base.scss
**Background**: The freja and delete eduid modals are too narrow 
**Summary**:
- I have added the freja and delete eduID modals to fullscreen styling at 823 px
- I have added code to override bootstrap styling @ 576px
- I have made all modals wider in fullscreen 
**Next steps**: 
- There seems to be an issue with breakpoints here as styling set @ 823px does not take effect, but randomly comes into play @ 741px
- Not too sure if it's bootstrap or other stylesheets that are overriding these styles
- Don't know if this affects all modals (most noticeable in Freja and Delete eduID - possibly because they have the most text)
=> Fixes narrow modals: freja and delete eduid

src/style/EduIDButton.scss
**Background**: The styling of the links (both as `<a>` and as `<button>`) are broken, see screenshots.
**Summary**:
- I have removed the blue background both for links (Freja modal) and for button links (change password button, delete eduID button and confirm labels Email/Phone number table)
- Background should be transparent at: hovers, press of button and no interaction
- I have also removed some commented out code for the related button.btn-link and at the smallest breakpoint
=> Fixes styling of links

.gitignore, src/style/DashboardMain.scss, src/style/base.scss
Background: makes layout less bloated for Dashboard and signup, more in line with login and home pages
bloated vs tighter spacing register: 
bloated vs tighter spacing dashboard:
=> Tighter spacing for Dashboard and Register pages

src/style/DashboardMain.scss
Fixed styling of h3 headers so they don't overlap with other text as per the image (seen on in Change Password and Verify Identity pages)
=> Fixes styling of overlapping h3 header 

src/entry-points/dashboard.js, src/entry-points/public-path.js
This PR inserts the cookie value of the bundle-version cookie between the host and the path configured as webpacks publicPath.
No cookie:
http://html.eduid.docker/static/front-build/1fafbdf8698be516791daafcbfef5104.ttf
bundle-version=beta1
http://html.eduid.docker/beta1/static/front-build/1fafbdf8698be516791daafcbfef5104.ttf
=> Set publicPath dynamically if the bundle-version cookie is set

src/containers/Footer.js
- Updates the naming of the faq link in the container to match the name in the store
:warning: **Users will be navigated to the Swedish FAQ regardless of what language is set in the dashboard. Users will then have to scroll to the bottom of the FAQ to change the language.**
=> Adds href to help/FAQ link in footer

plugins/eduid_action.mfa/index.js, plugins/eduid_action.mfa/public-path.js, plugins/eduid_action.tou/index.js, plugins/eduid_action.tou/public-path.js, src/entry-points/plugin-common.js
Apparently importing public-path in plugin-common did not cut it. If there is a better way to achieve a "direct import" than triplicating the public-path.js file, please advise :)
I should say that I tried require("entry-points/public-path") but it did not change the path.
=> Apparently importing public-path in plugin-common did not cut it

src/components/ChangePasswordForm.js
Disable the button in the password change form when the form is invalid
=> disable change password button when form not ready

src/login/styles/_buttons.scss, src/style/EduIDButton.scss
One remaining button still has overflowing text in the Swe translation (as described in [issue 222](https://github.com/SUNET/eduid-front/issues/222)).
Screenshots of issue and fix:
**Summary**: 
- `font-size: 0.9rem` on all buttons at screen sizes below 414px
- This fix has been added to two files:  
- *src/style/EduIDButton.scss:* which currently is controlling the styling of this (and most) buttons 
- *src/login/styles/_buttons.scss:* in preparation for the future when all buttons will be styled from here 
---
=> Mobile fix: Button text too big on smallest screen (Iphone 5/SE, 320x568)

src/components/Email.js, src/components/Emails.js, src/components/Mobile.js, src/components/NinForm.js, src/containers/Emails.js, src/containers/Mobile.js, src/tests/Emails-test.js, src/tests/Mobile-test.js
Pressing Enter when adding data to a few specific inputs reloads the page rather than execute the desired action (most described in [issue 193](https://github.com/SUNET/eduid-front/issues/193)). 
The following inputs have been fixed to execute the desired action both on button click and on Enter: 
- Settings > Phone (adding mobile number)
- Settings > Email (adding email address) 
- Register (registering email address)
- Profile > VerifyIdentity link > Nin input (this input had an old "fix" that blocked all action on submit) 
Summary: 
- in the first two inputs an `onSubmit={}` has been added to the `<form>` html element and `e.preventDefault()` has been added before dispatching the action 
- the third has had a `<div/>` changed into a `<form/>` element and a `onSubmit={}` added
- The …
=> Fixes: Stopping page reload on Enter

src/style/DashboardMain.scss, src/style/Nins.scss
Large spacing between data listed in profile: name, national identity number, email address and phone number (as described in [issue 220](https://github.com/SUNET/eduid-front/issues/220)). 
> Note: This only fixes this issue in mobile (`max-width: 786px`) as I have deemed that to be more urgent than nay other format. I am aware that any large and awkward spacing also needs to be addressed in desktop at a later stage.
issue and fix: 
**Summary:** 
- narrowed space between the data elements (`grid-row-gap` and `grid-column-gap` to 0)
- narrowed the line height of the actual data (from `line-height: 1.5` to `line-height: 1.2`)
- reduced the space around the nav (removed `margin: 20px 0` ) and made the nav stack at a wider screen width (from `414px` to `568px`)
=> Mobile fixes: Reduces spacing in the Profile (issue #220)

src/components/ConfirmModal.js
The `Modal` component from reactstrap does not have a handleConfirm prop.
=> Modal from reactstrap has no handleConfirm prop

src/components/DashboardMain.js, src/style/base.scss
Summary: 
- adds a class to link with `display: none`
=> Hides opt-in beta link 

src/style/base.scss
=> Actually hides opt-in beta link

src/components/Email.js, src/components/SignupMain.js, src/style/SignupMain.scss
**Summary:** 
- imported missing stylesheets
- adds similar styling to before break 
- stacks input and button @ `823px`
- button has full width @ `768px`
---
---
=> Fixes broken styling on Register page

src/components/ChangePasswordForm.js, src/tests/ChangePasswordForm-test.js
**Summary**:
- Display of a suggested value has been reverted back to a disabled input
---
=> Fix for validation of save button (when password is suggested)

src/components/NinDisplay.js
**Summary:**
- id `nin-number` added in on `<p>` holding the user nin 
---
=> Fix for mobile vetting (following change in css import for DashboardMain) 

i18n/src/login/translation/defaultMessages/errors.json, i18n/src/login/translation/defaultMessages/generalApp.json, i18n/src/login/translation/defaultMessages/instructions.json, i18n/src/login/translation/defaultMessages/password.json, i18n/src/login/translation/defaultMessages/register.json, i18n/src/login/translation/defaultMessages/userProfile.json, i18n/src/login/translation/messageIndex.json, src/components/Security.js, src/login/styles/_Security.scss, src/login/styles/_tables.scss, src/login/styles/index.scss, src/style/base.scss
**Summary:**
- Made font smaller at smaller screen widths
- Made verified text into a badge instead of button
- Applied the same styling to the security key table as the email address and phone number tables 
---
Desktop: 
Mobile:
=> Fix for broken security key table 

i18n/src/login/translation/defaultMessages/register.json, src/components/Email.js, src/components/Footer.js, src/containers/Footer.js, src/login/translation/defaultMessages/register.js, src/login/translation/languages/en.json, src/login/translation/languages/sv.json, src/login/translation/src/login/translation/defaultMessages/register.json
**Summary:**
- To display language in footer: 
- Removed rendering conditional: `this.props.is_configured` from `<Footer/>` component 
- Also removed from `<Footer/>` container 
- To fix that button was not disabled from start in Swedish translation: 
- changed the condition to disable the button from `props.invalid` to `!props.valid_email`  
---
=> Adds full footer (with language options) to register page

src/components/Footer.js
**Summary:** 
- code added to translation link in  `<Footer />` to set the lang attribute to match `this.props.language` 
- checked in Safari, chrome and Firefox
---- 
html before and after:
=> Sets the `<html lang="">` to match translation language

src/components/Header.js
user email showing in Header outside of dashboard (as described in issue #292 )
**Summary:** 
- moved email variable to conditional to only show in dashboard (url includes "profile")
---
=> REGISTER: Fix for header (incorrectly displaying user email)

src/components/Eidas.js, src/login/styles/_buttons.scss, src/login/styles/_links.scss, src/login/styles/_modals.scss
**Summary:** 
- Styled text in line with other modals:
- added numbers to list 
- moved "use Freja eID" link to the bottom of modal
- styled link as a button (adds styles for `a.btn` as the button really is a link)
=> Fixes styling for Freja eID modal 

src/login/styles/_SignupMain.scss, src/login/styles/_anti-bootstrap.scss
Addresses misalignment (described in issue #289 ) of: 
- input and button height
- button position when error message is displayed under input (only seen at Registration > add email input, as all other inputs have persistent descriptive text) 
**Summary:** 
- Added padding to top and bottom of inputs from `0.25rem` to `1.25rem` (creating a total of `3rem` = button height)
- Made items in `#register-from` align along baseline to no longer be affected by the appearance of error message
---
---
=> Fixes misalignment affecting inputs and the register email form

src/login/styles/_Header.scss
**Summary:**
- Adds `flex-wrap: wrap` to the two elements so they stack as soon as they don't fit on one line
---
=> Adds wrap to header text and email in dashboard

src/login/styles/_SignupMain.scss, src/login/styles/_links.scss
**Summary:** 
- made container holding both elements (text and link) `display: block`
---
=> Fix for broken register link on small screens

src/login/components/App/App.js, src/login/styles/_anti-bootstrap.scss, src/login/styles/_base.scss
.css ids and classes names of structural elements in `App.js` (equivalent to "Main" component of other apps) updated in line with example anatomy created in Figma
Summary: 
- `App.js`: replaces `#app-container`with `<Fragment>`
- `_base.scss`, `_anti-bootsrap.scss`: removed from sass 
**Note this is not a fix of any styling. It should not change/break the styling**
=> LOGIN: Updates naming of structural css in line with anatomy outlined in Figma

src/login/components/App/App.js, src/login/styles/_anti-bootstrap.scss, src/login/styles/_base.scss
.css ids and classes names of structural elements in `App.js` (equivalent to "Main" component of other apps) updated in line with example anatomy created in Figma
**Summary:** 
- replaces `#content` with `#panel` in both `App.js` and `_base.scss`
**Note this is not a fix of any styling. It should not change/break the styling.**
=> LOGIN: Updates naming of structural css in line with anatomy outlined in Figma 

src/components/AccountCreated.js, src/components/Captcha.js, src/components/CodeVerified.js, src/components/Email.js, src/components/EmailInUse.js, src/components/ResendCode.js, src/components/SignupMain.js, src/login/styles/_typography.scss
.css ids and classes names of structural elements in `SignupMain.js` (equivalent to "Main" component of other apps) updated in line with example anatomy created in Figma
- remove `div .dashboard-wrapper`
- replace `#register-container` to `#content` 
@src/components/AccountCreated.js 
@src/components/Captcha.js 
@src/components/CodeVerified.js 
@src/components/Email.js 
@src/components/EmailInUse.js
@src/components/ResendCode.js 
@src/components/ResendCode.js
@src/components/SignupMain.js 
@src/login/styles/_typography.scss 
_Before_
_After_
=> SIGNUP MAIN: Updates naming of structural css in line with anatomy outlined in Figma 

plugins/eduid_action.tou/component.js, plugins/eduid_action.tou/style.scss, src/components/ActionWrapper.js, src/components/Email.js, src/login/styles/_typography.scss
.css ids and classes names of structural elements in SignupMain.js updated in line with example anatomy created in Figma
- Remove `.text-content`
- Change className .`sub-headin`g to `.heading`
- Remove `#content .heading` styling
- Import Input from LoginApp to have same styling as Login
_Before_
_After_
=> SIGNUP: Updates naming of structural css in line with anatomy outlined in Figma

src/components/PersonalData.js
- first name (given_name) and last name(surname) are missing place holders.
- added `placeholder={props.translate("pd.given_name")} placeholder={props.translate("pd.surname")}`
**before and after**
=> INPUT: Add placeholder in given_name, surname fields

src/components/VerifyIdentity.js
A quick refactor of `<VerifyIdentity/>` to be able to follow more clearly how the vetting buttons are rendered and in particular see how `<OpenidConnect/>` works.
**Summary:**
- This is by no means a perfect job just a quick restructure of a component that was an even greater mess to begin with
- component now restructured into separate functions:
```
<VerifyIdentity_Step1 />
<Number added> (if nin is verified) 
<AddNumber> (if nin is not verified) 
<AddNin/> (the nin input/display of added nin - which has its own complicated render logic that I am not going to touch now)
<VerifyIdentity_Step2 />
<VettingButtons>
```
Note, as this is not a full path for group management, I will keep it separate from master and request that it is merged into a group management path branch
Next steps:
- …
=> VETTING: Refactor of <VerifyIdentity> to be able to better follow how vetting buttons render

src/components/LetterProofing.js, src/components/VerifyIdentity.js, src/containers/LetterProofing.js, src/tests/VerifyIdentity-test.js, src/vetting-registry.js
As described in issue #364 , the vetting button should be disabled if there is no nin. This PR disables the post and phone buttons when no nin is added and makes the modal show when valid nin is added. 
**Summary:** 
- restructures `VerifyIdentity` component:
- splits original code into multiple new functions: 
- `<VerifyIdentity_Step1>`: holds text for top of page and for step 1 of the verify identity process  (adding a nin)
- `<AddNumber>`: Text when identity (`nin`) is not verified
- `<NumberAdded>`: Text when identity (`nin`) is verified
- `<VerifyIdentity_Step2>`: Holds the text for step 2 of the verify identity process  (vetting nin)
- the rendering of the vetting buttons is kept separate (moving it causes redux form to render and destroy the confirmation code input in an infinite …
=> VETTING: Disables/enabled post and phone vetting buttons based on valid nin

i18n/src/login/translation/defaultMessages/userProfile.json, src/login/translation/defaultMessages/userProfile.js, src/login/translation/languages/en.json, src/login/translation/languages/sv.json, src/login/translation/src/i18n-messages.json, src/login/translation/src/login/translation/defaultMessages/userProfile.json
I update  a skipped suggestion in issue https://github.com/SUNET/eduid-front/issues/354
- Vetting buttons in English 
"For those registered at their current address" -> "For you registered at your current address"
"For those with a phone registered in their name"->"For you with a phone registered in your name"
"For those able to create a Freja eID by visiting one of the authorised agents"-> "For you able to create a Freja eID by visiting one of the authorised agents"
- Vetting buttons in Swedish 
"För de som har eller kan skapa Freja eID genom att besöka ett ombud i Sverige"->"För dig som har eller kan skapa Freja eID genom att besöka ett ombud i Sverige"
"För de som har ett telefonabonnemang i sitt eget namn"->"För dig som har ett telefonabonnemang i ditt eget namn"
"För de som har …
=> SWEDISH TRANSLATION: Adjust Swedish text in vetting buttons and help text

src/components/VerifyIdentity.js
Issue https://github.com/SUNET/eduid-front/issues/380
the positioning of the vetting buttons in desktop mode changed
but now returned to previous position 
- replace  `<div key="1" id="nins-btn-grid" />` outside of vetting buttons
before
after
=> VETTING BUTTONS: Fix positioning of vetting buttons

src/login/styles/_Emails.scss, src/login/styles/_SignupMain.scss, src/login/styles/_buttons.scss
misalign button in firefox browser 
issue https://github.com/SUNET/eduid-front/issues/387
- Comment out` align-items: baseline;`` #emailsview-form`,` #phonesview-form`, `#register-form`
- Add `margin-top: 0` in `#email-button `and `#mobile-button`
------
**Before and After(Register)**
**Before and After(Settings)**
=> BUTTON: Misalign button in firefox

src/components/VerifyIdentity.js
issue https://github.com/SUNET/eduid-front/issues/389
- when `verifiedNinStatus` is true, display `recoverIdentityTip`
- `!this.props.verifiedNinStatus` to show vetting buttons when user have not verified 
----
----
=> CONFIRM IDENTITY: Uncaught ReferenceError on Identity tab

i18n/src/login/translation/defaultMessages/userProfile.json, src/login/translation/defaultMessages/userProfile.js, src/login/translation/languages/en.json, src/login/translation/src/login/translation/defaultMessages/userProfile.json
Issue https://github.com/SUNET/eduid-front/issues/391
translation`nin_display.profile.main_title` is not capitalised
- change `nin_display.profile.main_title` (Engilsh) text ` id number` to `Id number `
=> Change nin_display.profile.main_title text lowcase to capitalise 

src/components/Settings.js, src/login/components/App/DashboardApp/Settings/Groups/Groups.js, src/login/styles/_base.scss
Further evolves the logic for the parent `<Groups/>` in preparation for taking on further children.
**Summary:** 
1. Refine component structure 
- The first `<div>` has been changed into an `<article>` and a proposal to make all the different components in settings the same has meed added as an issue (#418 ) 
- Styling to make section consistent with others has been added to `article {}` in `_base.scss`
2. Instructions added as comment for complete transparency of intention (lines 7-11 of file):
```
// this component should:
// 1. take in text to fill .intro h4 and .intro p (hardcoded at the moment)
// 2. be able to handle logic of create group button:
// - if wizard: hide button
// - if no wizard: show button
``` 
3. As described in above instructions wizard render logic has been added …
=> GROUP MGMT: Draft logic for <Groups/> parent 

i18n/src/login/translation/messageIndex.json, src/components/ConfirmModal.js, src/components/ConfirmModalForm.js, src/components/Security.js, src/login/styles/_inputs.scss, src/login/styles/_modals.scss, src/login/translation/languages/en.json, src/login/translation/languages/sv.json, src/login/translation/messageIndex.js, src/login/translation/src/i18n-messages.json, src/login/translation/src/login/translation/messageIndex.json
Replace new customInput for modal form
- Replace customInput
- Adjust styling according to figma https://www.figma.com/file/1uzAOgj9zgIpL6n7C0z24o/eduID%3A-website-anatomy?node-id=394%3A813
- Add placeholder(translate) for security key 
- Adjust padding-right for .form-control.is-invalid to avoid covering place holder text
----
- before and after (email confirm code) @1200px
- before and after (mobile confirm code) @1200px
- before and after (security code) @1200px
- before and after (email confirm code) @320px
- before and after (mobile confirm code) @320px
- before and after (security code) @320px
----
=> INPUT: implement custom input for confirm modal form

src/components/Email.js, src/components/GenericConfirmModal.js, src/login/styles/_modals.scss
for reusability I have remove modal code in `Email.js` and added a Import` GenericConfromModal`
- this needed to send specific props for rendering different text and translation in button. `Email.js row 84`
```
acceptButtonText={this.props.translate("tou.accept")}
closeButtonText={this.props.translate("tou.cancel")}
acceptButtonId={"accept-tou-button"}
closeButtonId={"reject-tou-button"}
```
- props.mainText(props.tou) have a html tags `<ul/><li/>`so needed have a logic to check modal-id to display different modal-body
```
modalId === "register-modal" ?
<ModalBody 
dangerouslySetInnerHTML={{ __html: mainText }} 
/>
: 
<ModalBody>
<div>
<p>{mainText}</p>
</div>
</ModalBody>
```
- to display  button text in Emails.js (eng)"Accept" (Swe)"Godkänd" / (eng)"Cancel" (Swe)"Avbryt" …
=> MODAL: Import generic confirm modal for email(register)

src/components/Eidas.js, src/login/components/Modals/NotificationModal.js
Import NotificationModal component in Eidas.js. 
Separate 3 different functions` RenderModalBody, RenderAcceptButton, RenderCloseButton`
Functions follow render hierarchy.
**Please check Vetting button (FrejaeID) to see if it opens the modal.
Double check that link "What is Freja eID?" and "USE MY FREJA EID" navigates properly.**
---
Before (master)
After
---
=> MODAL: Import notification modal in Eidas

src/containers/Security.js
When adding a security key, the value didn't send to backend,  it caused below response.
"type": "POST_WEBAUTHN_WEBAUTHN_REGISTER_COMPLETE_FAIL"
This problem was caused by security key input value was undefined.
- Fixed: Description value change to **children[1].value**
----
**please check in response when adding a security key.**
---
=> SECURITY KEY: Fix undefined value for description

i18n/src/login/translation/defaultMessages/userProfile.json, src/components/LookupMobileProofing.js, src/login/translation/defaultMessages/userProfile.js, src/login/translation/languages/en.json, src/login/translation/src/i18n-messages.json, src/login/translation/src/login/translation/defaultMessages/userProfile.json
I have corrected spelling error in ` lmp.modal_reminder_to_confirm_title`
I have changed `Your number also needs to be confrimed `to `Your number also needs to be confirmed`
---
- Before/After
---
=> MODAL: Corrected spelling error for modal title by vetting phone

src/login/styles/_buttons.scss
Issue https://github.com/SUNET/eduid-front/issues/449
Issue https://github.com/SUNET/eduid-front/issues/406
After pressing confirm, the button will disappear even if the modal is cancelled. to activate the page need to be reloaded.
- it was caused due to overwriting button styling so I have added detailed class name to avoid overwriting styling  
----
- Before / After
=> ADD PHONE/EMAIL: Missing "confirm" button after resending or cancel verification code

src/components/VerifyIdentity.js, src/login/styles/_Nins.scss, src/login/styles/variables.scss
changed help text color under the vetting button depends on if id number is added or not.
- checking index 0(by letter) or 1 (by phone) and no id number, text color will be gray otherwise text color will be black.
----
- disabled button
- abled button
----
=> VETTING: change of vetting help text color triggered by added of NIN

src/containers/Footer.js
Currently available_languages in jsapps config is a list of lists but in the actions config it is a map. A map is also used in the backend. This change should let us use both until we remove the list of lists format.
=> Handle available_languages as both list of lists and map

src/login/styles/_buttons.scss
Issue https://github.com/SUNET/eduid-front/issues/454
When hovering past the disabled OK button it briefly (not able to catch in screenshot) has a gray outline which could indicate that it is clickable.
- Removed  `border: solid 1px transparent; `
=> MODAL BUTTON: Remove border to prevent hovering effect of disabled button

src/components/Security.js, src/login/styles/_buttons.scss, src/login/styles/_tables.scss
old security key table was unreadable in mobile mode and not balanced in the desktop mode.
[Figma design]( https://www.figma.com/file/IBBTDRxd5dKQa7Ltj0Hd0l/eduID%3A-website-user-flow?node-id=179%3A580)
I followed confirmed design. however spacing between columns is not exactly same as design because I used percentage of columns.
- Added className for table headings and width
`security-name: 36%`,
`security-creation-date: 21%`, 
`security-last-used-date: 21%`,
`security-verify-link: 17%`, 
`security-remove-data: 5%`
-  Display: none `security-creation-date` and `security-last-used-date` @ max-width: 568px
-  when Security Key name is too long, text will be cropped  and will display followed by dots.
`   white-space: nowrap;`
`   text-overflow: ellipsis;`
`   overflow: hidden;`
----- …
=> SECURITY KEY:  updated styling for security key table

src/login/translation/languages/sv.json
=> spelling: Personumret -> Personnumret

.github/workflows/run-tests.yaml, .travis.yml, Makefile
Move CI testing from Travis to Github Actions, since Travis has started requiring full write access to all the repositories in the organisation.
Two topics of possible further improvements here:
- The tests run with Node 10, just like on Travis. It is trivial to also run them with Node 12.x, but I don't know if that is desired.
- I added a separate step running 'npm audit' but did not make the build fail on that since it reports 894 vulnerabilities. I guess someone with some JS knowledge should run 'npm audit fix' and make a PR updating all those dependencies. For now, I made the CI continue even when 'npm audit' raises issues.
=> Replace travis with GitHub actions

src/login/components/GroupManagement/GroupList.js, src/login/components/GroupManagement/GroupManagementContainer.js
While going through the members and owners lists to establish a users' relationship with each group, the user itself was identified based on "username" (acquired via primary email address) and now we use `user_identifier` provided by the backend. 
**Summary:**
1.  Reduced the user/group relationship hack:
- removed functionality passing all user email addressed from the redux store and filtering out the primary one
- removed conditional to only filter primary address if alla email addresses were available 
- updated the creation of the user/group relationship object to check all member/owner identifiers against the `user_identifier`  
2. Removed component error handling
- Removal of `<GroupList/>` to render `null` if user/group relationship info is not available
=> GROUP MANAGEMENT: Replaces username for user_identifier in user/group relationship hack

src/tests/LetterProofing-test.js
Quick refactoring letter-proofing test for avoiding similar boilerplate code
- Added getFakeState function that return fakeStore where we can change what we want to change with arguments. 
that will avoid duplicated code and typing errors.
- Removed unused code
=> Refactoring letter-proofing test for using same base state

src/login/translation/languages/sv.json
issue https://github.com/SUNET/eduid-front/issues/489
correct spelling error in vetting button by post
- Brevet är giltig till -> Brevet är giltigt till
=> Fix minor spelling error, giltig to giltigt

src/components/Emails.js, src/components/Mobile.js, src/components/Security.js, src/login/components/LetterProofing/LetterProofing.js, src/login/components/Modals/ConfirmModal.js, src/login/components/Modals/ConfirmModalContainer.js
ConfirmModal has been updated with the new design in previous [PR 495](https://github.com/SUNET/eduid-front/pull/495) 
as we agreed I have moved the improved files to the new location(login). login is only temporary folder name so far.
so this PR is covering the move of ConfirmModal component file from `src/component` and container file from `src/containers` to `/login/component/Modals`
=> Migrating confirm modal components and container

src/login/components/GroupManagement/GroupManagementContainer.js, src/login/components/GroupManagement/Groups/EditGroup.js, src/login/components/GroupManagement/Groups/GroupListItem.js, src/login/components/GroupManagement/Groups/GroupsList.js, src/login/components/GroupManagement/Groups/GroupsParent.js, src/login/redux/reducers/groupsReducer.js
Listing of groups has been updated to render the updated data structure that describes a user's role in each of their groups. 
Summary: 
- The previous "hack" that created this object has been removed (GroupManagementContainer.js)
- The data reaching the app has been renamed from `uniqueGroups` to `groupsData` and updated throughout (GroupManagement, GroupsList and GroupListItem)  
- props have been destructured in places where the data is nested deep in the object (EditGroup and GroupListItem)
---
----
=> GROUP MANAGEMENT: Updates group data render after new backend data structure 

.eslintrc.js, src/reducers/DashboardConfig.js, src/reducers/Emails.js, src/reducers/LetterProofing.js, src/reducers/Mobile.js, src/reducers/Nins.js
The "`extends`": "`eslint:recommended`" property in a configuration file enables this rule.
This rule disallows lexical declarations (let, const, function and class) in case/default clauses. The reason is that the lexical declaration is visible in the entire switch block but it only gets initialized when it is assigned, which will only happen if the case where it is defined is reached. 
To ensure that the lexical declaration only applies to the current case clause wrap your clauses in blocks. 
This PR, is for **no-case-declararions** : 
- Remove **no-case-declarations: off** in .eslint.js
- Use **{ }** to create the block scope with case
=> ESLINT: Turn on eslint rules:  no case declarations by removing "off" in rules

src/components/PersonalData.js
**When creating a new account**, user is required to fill all personal information data inputs before the "Save" button is enabled
Previously only one input was required to enable the "Save" button
---
- Before and after
---
**please, create a new account and test to fill  the personal data**
=> PERSONALDATA:  Button disabled when input is empty

webpack.config.js, webpack.prod.config.js, webpack.staging.config.js
previous PR #548 was not able to load errors.html for staging and production. now I have added/separated htmlwebpackplugin for each environment config. 
- Development
- Staging
- Production
=> ERRORS: load errors html for staging and production

i18n/src/login/translation/defaultMessages/errors.json, src/components/NinDisplay.js, src/login/translation/defaultMessages/errors.js, src/login/translation/src/login/translation/defaultMessages/errors.json, src/notify-middleware.js
fix for issue [564](https://github.com/SUNET/eduid-front/issues/564)
`id=nin-number` was removed so data nin was not found, så text "testing" was sent instead of nin number.
I added`id=nin-number` to p tag and added specific error message for "nin needs to be formatted as 18|19|20yymmddxxxx".
this error message will show when user send incorrect format of nin (but we have a input validation so this should not happen)
=> IDENTITY: Fix Incorrect nin data and specific fault massage added

src/notify-middleware.js
not able to see error message when failed letter proofing 
After failed letter proofing an error(can not read property) in console
- before fix
- after fix
=> NOTIFICATION: Fix console log error and show correct error message after letter proofing failed

webpack.prod.config.js
Fix for referenceError in production 
- Remove one of the duplicated `webpackProd.plugins` array and add `htmlWebpackPlugin `within `initialConfigPlugin` in the array
=> Fix: ReferenceError in production

src/login/components/LoginApp/LoginApp.js
This PR updates the path at which LoginForm renders to align with the new idp. 
> The updated login app will start with a reference at the end of the URL. The reference is only relevant for the login flow. It will be sent to the backend together with user credentials and enables the backend to evaluate what steps of security the user needs to complete to gain access to the end service. (**See at the bottom how to activate the updated idp**). **Remember to deactivate when working on other things!**
**Summary:**
The path at which the LoginForm renders is updated:  
- from `/login/` 
- to `/login/${urlCode}`
---
---
**Accessing the updated idp**: 
1. Remove comment (`#`) from `login_bundle_url` in file `/opt/eduid/src/eduid-developer/config/config.yaml`:
```
```
2. Restart `eduid_idp_1`
3. …
=> LOGIN: Update to path that renders login form 

src/login/components/LoginApp/LoginApp.js, src/login/components/LoginApp/ResetPassword/ResetPasswordForm.js, src/login/components/LoginApp/ResetPassword/ResetPasswordMain.js
This PR is for adjusting of reference url code.
Due to the lates change of the login url, there is an update to the URL link needed to return to login page by the return link button in reset password page.
Now when directed from the reset password page to the login page, the URL reference is included.
- added setState urlCode on componentDidMount
- inject "urlCode" props to ResetPasswordForm
- changed href="login" to  href={`/login/${props.urlCode}`} in ResetPasswordForm.js
=> RESETPASSWORD: Add return to login with url ref

src/login/components/Inputs/EmailInput.js, src/login/components/Inputs/InputWithIcons.js, src/login/components/Inputs/PasswordInput.js, src/login/components/LoginApp/Login/Login.js, src/login/components/LoginApp/Login/UsernamePw.js, src/login/components/LoginApp/Login/UsernamePwForm.js, src/login/components/LoginApp/LoginApp.js
This PR adds prop types to relevant props. For props crucial to render logic `.isRequired` has been added.
**Summary**:
1. prop types added to files: 
- LoginApp/Login
- UsernamePw/UsernamePwForm
- EmailInput/PasswordInput
- InputWithIcon
=> LOGIN: Adds prop types to props relevant to username and password page

src/login/components/Inputs/InputToggleShowHide.js, src/login/components/LoginApp/Login/Login.js, src/login/components/LoginApp/Login/TermsOfUse.js, src/login/components/LoginApp/Login/UsernamePw.js, src/login/styles/_Login.scss
This PR adds terms of use text and button to the /tou/ page.
**Summary**: 
1. Renders hardcoded terms of use text 
2. Adds styling
- the _Login.scss file has been refactored
> Note: Due to the current forced page flow (usernamePw > tou> mfa) adding incorrect details currently allows users to advance to the Terms of use page
**Known limitations**: 
- The text is currently hardcoded in the component
- The accept button does not work 
- Reloading the terms of use page takes the user back to the start of the forced login flow 
---
---
=> LOGIN: Render text on terms of use page

src/login/styles/_Login.scss, src/login/styles/_inputs.scss
Relocate `.password-input `styling code from `_Login.scss` to` _inputs.scss`
=> Relocating of password-input to common styling to use in both login and reset password

src/login/components/LoginApp/Login/Login.js, src/login/components/LoginApp/Login/SubmitSamlResponse.js, src/login/redux/actions/postRefLoginActions.js, src/login/redux/actions/postUpdatedTouAcceptActions.js, src/login/redux/actions/postUsernamePasswordActions.js, src/login/redux/reducers/loginReducer.js, src/login/redux/sagas/login/postUpdatedTouAcceptSaga.js, src/login/redux/sagas/login/postUsernamePasswordSaga.js, src/login/redux/sagas/login/postWebauthnFromAuthenticatorSaga.js, src/login/redux/sagas/rootSaga/loginSagas.js, src/tests/sagas/postUpdatedTouAcceptSaga-test.js, src/tests/sagas/postUsernamePasswordSaga-test.js
This PR adds functionality to complete the login process for users with a registered security key. 
> Note that the forced navigation USERNAMEPW > TOU > MFA has been disabled (commented out). The commented out code will have to remain until the tou page is finalised.
**Summary:**   
1. Adds functionality to complete the login process: 
- loginReducer: `action.payload.parameters` added to redux store when `action.payload.action === "FINISHED"` 
- Login: `next_page === "FINISHED"` renders new child`<SubmitSamlResponse />`
- **NEW** `<SubmitSamlResponse />`:  hidden form submitted on load in order to POST `SAMLResponse` to `targetUrl`
2. The forced navigation has been disabled in favour of the repeated calls to /next on _SUCCESS: 
- Forced navigation code commented out in: loginReducer and …
=> LOGIN: Adds completion of login process with security key

src/login/translation/defaultMessages/instructions.js, src/login/translation/src/login/translation/defaultMessages/instructions.json
This PR fixes three broken text strings rendered on the plugin mfa page.
**Summary**: 
- adds default messages for the relevant message ids 
- translations untouched
---
---
=> PLUGINS: fixes broken text strings rendered on mfa page

plugins/eduid_action.mfa/component.js
set correct path to actions as next
backend no longer supports base64 encoded redirect
=> set correct path to actions as next

src/login/styles/_Login.scss, src/login/styles/_Notifications.scss, src/login/styles/_base.scss, src/login/styles/_buttons.scss, src/login/styles/_forms.scss, src/login/styles/_inputs.scss, src/login/styles/variables.scss, src/login/translation/defaultMessages/login.js, src/login/translation/languages/en.json, src/login/translation/languages/sv.json, src/login/translation/src/login/translation/defaultMessages/login.json
This PR adds styling to login flow to make it functional on smaller screen. Smallest screen width at `320px` is prioritised but some changes take effect from `414px`.
**Summary**: 
1. Sets outer margin at `320px` to `1 rem`
- also adjust the margins of the error messages at this size 
2. Removes padding from inside buttons, allows for better centring of text when two lines
3. Adds custom breakpoint for mfa page at `382px`
- represents the .option (`width: 350px`) and margins (`16px`) on each side 
---
---
=> LOGIN: Adds mobile styles to login flow

src/login/redux/sagas/login/postRefForWebauthnChallengeSaga.js, src/login/redux/sagas/login/postTouVersionsSaga.js, src/login/redux/sagas/login/postUpdatedTouAcceptSaga.js, src/login/redux/sagas/login/postUsernamePasswordSaga.js, src/login/redux/sagas/login/postWebauthnFromAuthenticatorSaga.js, src/tests/sagas/postUpdatedTouAcceptSaga-test.js, src/tests/sagas/postUsernamePasswordSaga-test.js
This PR replaces hardcoded urls in most login sagas for a dynamic url provided by the backend and stored in `state.login.post_to`. 
**Summary**:
1.  All login sagas sending user data to the backend now have dynamic urls
- Username and Password: `postUsernamePasswordSaga`
- Tou: `postTouVersionsSaga`, `postUpdatedTouAcceptSaga`
- Mfa: `postRefForWebauthnChallengeSaga`, `postWebauthnFromAuthenticatorSaga`,
2. Dynamic urls are: 
- provided by: `/next` endpoint
- stored in redux store: `state.login.post_to`
3. **TEST**s updated to reflect this change: 
-   `postUsernamePasswordSaga-test.js` and `postUpdatedTouAcceptSaga-test.js`
=> LOGIN: replaces hardcoded api urls with dynamic ones provided by backend

src/login/redux/sagas/login/postRefLoginSaga.js, src/tests/sagas/postRefToLogin-test.js
This PR adds error handling for the `/next` endpoint
**Summary:** 
1. Saga file has been cleaned up to improve legibility
2. **TEST**: improved legibility and added `_FAIL` response test
**Known limitation**:
- message `login.bad_ref` does not yet have a translation and triggers the generic error message 
---
---
=> LOGIN: Expected error message for /next endpoint

src/login/components/Inputs/PasswordInput.js, src/login/components/LoginApp/Login/FrejaeID.js, src/login/components/LoginApp/Login/MultiFactorAuth.js, src/login/components/LoginApp/Login/SecurityKey.js, src/login/components/LoginApp/Login/UsernamePw.js, src/login/styles/_inputs.scss, src/login/translation/languages/en.json, src/login/translation/languages/sv.json, src/login/translation/messageIndex.js, src/login/translation/src/login/translation/messageIndex.json
This PR adds the green chcekmark back in to valid inputs when they are autofilled.
**Summary:**
- Added to `<PasswordInput/>`:
- Fontawesome checkmark icon to input
- styling of icon to render next to show/hide button
> **NOTE** this change only applies to `<Form>` that imports `<PasswordInput />` and with `name="current-password"` (only password input in the UsernameAndPwForm). All previous code is intact.
---
---
=> LOGIN: Adds checkmark when valid input on autofill

src/login/components/Inputs/CustomInput.js
This PR removes duplicate `id="email"` in the username and password form. Both the `<div>` parent wrapping the email input and the `<input>` itself had the same "email" id.
> `id` removed from `<input>` as they are standard but not strictly necessary. It was most likely added to automatically pair `<input id={""}>` with `<label  htmlFor={""}>` essential for checkboxes used for group management. The checkboxes ended in separate files and the automatic pairing is less essential for non-checkbox inputs. 
**Summary:** 
1. The "id={name}" attribute removed from the input, remaining only on the wrapper 
- successfully tested login and reset password to ensure no error introduced 
- signup to ensure no error introduced in earlier render of inputs
=> LOGIN: Removes duplicate html id attributes from login email input 

src/login/components/Inputs/CustomInput.js, src/tests/PersonalData-test.js
This PR sets an id attribute on the email`<input>` in the UsernamePwForm. Its parent `<div>` has been given a new id attribute. These need to be set apart for automated testsing to work.
**Summary:**
1. `<input>` now has `id={name}` 
2.  `<div>` parent element now given `id={${input.name}-wrapper}`
99,9% of the inputs will undergo automatic testing to find anything that breaks following this change.
=> LOGIN: Sets an id on the login email input and new id for parent div

src/login/components/LoginApp/ResetPassword/ResetPasswordSuccess.js, src/login/translation/defaultMessages/password.js, src/login/translation/languages/en.json, src/login/translation/languages/sv.json, src/login/translation/src/login/translation/defaultMessages/password.json
This PR is to change link description text to `go to eduID` when finished reset password, to reflect the link routing
Previous text "return to Login" even though the link was to the "main page"
---
- in english
- in Swedish
--
=> RESETPASSWORD: Change link description text

src/login/components/LoginApp/ResetPassword/ExtraSecurity.js, src/login/redux/actions/postResetPasswordActions.js, src/login/redux/reducers/resetPasswordReducer.js, src/login/styles/_ResetPassword.scss
This PR is to remove "enter code" link inside loop. API call to "/extra-security-phone/" for reset password phone_index is not needed. so now there will be only one link to enter phone code form below all individual phone number sms request buttons.
- Removed unnecessary function for `selectedPhoneInfo`
- Moved link `toPhoneCodeForm` to outside of phone button loop
- Adjust styling for extra security buttons after added unique id for extra security buttons
---
- Before
- After
---
=> RESETPASSWORD: Remove enter code link from extra security phone button loop

src/login/translation/defaultMessages/password.js, src/login/translation/languages/sv.json, src/login/translation/src/login/translation/defaultMessages/password.json
This PR is to fix an issue in staging, there is a missing translation of the text, it is for reset password button.
I adjusted the text  `used.email-in-use` to `An eduID is already using {email}` in English and `Ett eduID konto använder redan {email}` in Swedish, and added value to Swedish text for displaying email address
- Added used.reset-password in password.js
- Adjusted Swedish text E-postadressen används redan -> Ett eduID konto använder redan {email}
---
- in English (before)
- in English (after)
- in Swedish (before)
- in Swedish (after)
---
=> SIGNUP:  Fix unknown message id in reset password button

src/actions/Captcha.js, src/containers/Email.js, src/reducers/Captcha.js
This PR is to fix an issue with reregistration of new accounts, if the user is adding an incorrect email adress and notices this in the final stage "email sent", if the user is returning to "register page" using the browser "previous" button, the "captcha" function didn't allow a new email adress to be register.
- Added function `makeCapthaButtonAvailable()` to activate button onclick accept TOU
- Added dispatch remove notification onclick accept TOU
**To test follow this steps:**
1.  Register a new user 
2.  Use the "previous " button in browser twice to be abele to change email adress
3. Change the email and try register 
4. "captcha" should work and a email should be sent to the "new email adress"
=> SIGNUP: make available to register new account after registering an incorrect email 

src/login/styles/_ResetPassword.scss
This PR moves the send button for reset password input for email, instead of having the button at the same row as the input, it is now below the input field to allow display of long email address 
---
- desktop 1200px
- mobile 360px
---
=> RESETPASSWORD: Move the send link button for reset password form to allow longer email addresses

src/login/components/LoginApp/LoginApp.js, src/login/components/LoginApp/ResetPassword/ResetPasswordMain.js
This PR is to redirect all users from `/reset-password/` to `reset-password/email`
at this time the `/reset-password/` page is blank, this PR will redirect all users who write url "/reset-password/" to reset password main page (reset-password/email)
To Test this PR:
check if this url "https://html.eduid.docker/reset-password" redirect to "https://html.eduid.docker/reset-password/email"
=> RESETPASSWORD: Redirect from url reset-password to reset-password/email

src/login/components/LoginApp/ResetPassword/ExtraSecurity.js, src/login/components/LoginApp/ResetPassword/PhoneCodeSent.js, src/login/components/LoginApp/ResetPassword/SetNewPassword.js, src/login/styles/_ResetPassword.scss, src/login/styles/_buttons.scss, src/login/translation/defaultMessages/password.js, src/login/translation/languages/en.json, src/login/translation/languages/sv.json, src/login/translation/src/login/translation/defaultMessages/password.json
This PR is to add a "go back" button for user who has an extra security.
the button will make it possible for the user to go back to the page where they can select another option of the "extra security"
And if the user fails to set a new password they are able to return to the extra security page
---
---
=> RESETPASSWORD: Add a "go back" button to extra security

src/containers/Security.js
This PR addresses issue [683](https://github.com/SUNET/eduid-front/issues/683), where adding a security key has stopped working. In fact, the website crashes on OK button click because `description` variable in the `Container` is not pointing to the input value.
**Summary:**
1. DOM traversal shortened to pick up security name value
---  
---
=> DASHBOARD: Alters DOM traversal to get value from security key input when adding new key

src/login/components/LoginApp/ResetPassword/SetNewPassword.js, src/login/styles/_ResetPassword.scss, src/login/translation/defaultMessages/password.js, src/login/translation/languages/en.json, src/login/translation/languages/sv.json, src/login/translation/src/login/translation/defaultMessages/password.json
To explain the function of the `Copy to clipboard` button/ icon, I have added tool tip with hover effect. 
When hovering the icon, the information `Copy to clipboard(eng) / Kopiera till urklipp(swe)` will display
When icon has been clicked, the information `Copied!(eng) / Kopierat!(swe)` will be displayed
---
- Hover effect (Desktop mode)
- onClick
- Hover effect (Mobile mode)
- onClick
---
=> RESETPASSWORD: Add  hover effect information to copy icon for new password

src/components/EmailInUse.js, src/containers/EmailInUse.js
When user is attempting to signup using an email address that is already in use, there is an option to go to reset password. the button used the old url.
This PR is to change the old url to new reset password url from config ("https://html.eduid.docker/reset-password/")
---
---
=> RESETPASSWORD: Change link to new reset password url

src/login/components/App/App_reducer.js, src/login/components/LoginApp/Login/UsernamePw.js, src/login/components/LoginApp/ResetPassword/ResetPasswordMain.js, src/login/redux/actions/loadingDataActions.js, src/login/redux/sagas/resetpassword/postResetPasswordSaga.js, src/login/styles/_Login.scss, src/tests/ResetPassword-test.js, src/tests/sagas/postResetPasswordSaga-test.js
This PR is to prevent the user to click multiple times on the send link.
so I have disabled the button when `request_in_progress` state is true 
when `request_in_progress` state is false (request is completed), the button will be active again for the user.
---
- **LOGIN PAGE** `forgot your password` link will deactivate when request is being progressed
- **RESET-PASSWORD PAGE** ` send email button` will deactivate when request is being progressed
---
**To test this PR**, add delay function in `postResetPasswordSaga.js` to show that the button is disabled 
```
**const delay = (ms) => new Promise(res => setTimeout(res, ms))**
export function* postEmailLink() {
...
try {
yield put(requestInProgress());
**yield delay(10000);** 
```
=> RESETPASSWORD: disable send email link when request is being progressed

src/login/styles/_Notifications.scss, src/login/styles/_base.scss
This PR is to fix the issue with notification messages covering content on small size screens
- Removed height: 3rem for notification-area
- Added padding-top: 2rem for horizontal-content-margin
Please render any error and display at any page on small size screen to confirm that the fix solve this issue 
---
- Before 
- After
---
=> NOTIFICATION: Fix issue with notification message covering content

src/login/components/LoginApp/ResetPassword/CountDownTimer.js, src/login/components/LoginApp/ResetPassword/EmailLinkSent.js, src/login/components/LoginApp/ResetPassword/PhoneCodeSent.js, src/login/styles/_ResetPassword.scss, src/login/translation/defaultMessages/password.js, src/login/translation/languages/en.json, src/login/translation/languages/sv.json, src/login/translation/src/login/translation/defaultMessages/password.json
depending on if the count down timer for "resend phone code"/"resend email link" is active or not the description text has been adjusted
- English: when not active - when timer is active
resend link - resend link **in XX:YY**
- Swedish 
skicka länk igen - Skicka länk igen **om XX:YY**
---
- email link 
-phone code
---
=> RESETPASSWORD: Adjust description text for resending phone code/email link depending on if count down timer is active or not

src/login/components/Inputs/CustomInput.js, src/login/components/Inputs/ResetInputToggleShowHide.js, src/login/components/LoginApp/ResetPassword/SetNewPassword.js
on click input "repeat new password", browser asking if the user want to use a suggested password from browser.
- change type from password to text
- move "autoComplete=new password" from repeat password input to new password
PS. this PR will remove the "show/hide" function for "repeat new password" input field DS.
---
- before (safari)
- before (fire fox)
-before(chrome)
- after
---
=> RESETPASSWORD: Prevent browser suggested password in "repeat new password" field

src/login/components/Inputs/EmailInput.js, src/login/components/LoginApp/Login/UsernamePw.js, src/login/styles/_Login.scss, src/login/translation/defaultMessages/errors.js, src/login/translation/languages/en.json, src/login/translation/languages/sv.json, src/login/translation/messageIndex.js, src/login/translation/src/login/translation/defaultMessages/errors.json, src/login/translation/src/login/translation/messageIndex.json
This PR addresses some design-related feedback on the login form page.
**Summary:**
- Swaps position: Login button and "Forgot password" link  
- Changes the following text: pw placeholder, error text for required data, removed help text on the login form email address input
- Register here: right-aligned in both languages 
---
---
=> LOGIN: Addresses cosmetic design feedback on the login form 

src/components/DashboardNav.js
=> DASHBOARDNAV: Inative settings link highlighting  when click advanced settings 

src/login/styles/_SignupMain.scss, src/login/styles/_base.scss
Previous PR, changed id for element div id={email-wrapper}  but styling had not been updated on sign up. now input field size return to previous size.
---
- before fix
- after fix 
---
=> SIGNUP: Update styling for id  after latest change of uniq id

src/login/styles/_buttons.scss
This PR is to update new disabled button, from gray color to `primary orange color `with `opacity 40%`, hex color code to variable in `_button.scss `
---
- Login page
- Reset password (set-new-password)
- Dashboard (name and langs)
- Modal (settings - security)
- Singup
---
=> BUTTON: Update of disabled button

src/login/components/LoginApp/Login/SecurityKeySelected.js, src/login/redux/sagas/rootSaga/loginSagas.js
This PR is to fix POST IDP MFA AUTH FAIL on login with security key 
To test this PR
- comment out  `document.forms[0].submit();` in SubmitSamlResponse then try login authentication with security key
---
- before
- after
---
=> LOGIN: Removal of unnecessary saga call

src/components/Security.js
I have tested with my mobile phone and I can still not rendering "platform auth button"
However, I see the security button has been changed to "secondary option" it means platform auth is available.
I changed from  "true && expression" to "condition ? true : false" same expression as className. 
"true && expression" cause the problem, skipping re-rendering of updated state.
and I moved button inside render for readability
=> ADVANCEDSETTINGS: Change expression to "condition ? true : false" for platform auth button

src/login/redux/sagas/resetpassword/postExtraSecurityPhoneSaga.js, src/login/translation/languages/sv.json
Fixes #774
engångsverifieringskod -> engångskod
---
---
=> RESETPASSWORD: Add missing status message when OTP has been sent

i18n/src/login/translation/messageIndex.json, src/components/ChangePasswordForm.js, src/login/translation/languages/en.json, src/login/translation/languages/sv.json, src/login/translation/messageIndex.js, src/login/translation/src/i18n-messages.json, src/login/translation/src/login/translation/messageIndex.json
=> CHANGEPASSWORD: Remove html tag from chpass.help-text

src/components/DashboardNav.tsx
found a missing path which caused the currently active page indication to be inactive
now sorted so user always can see what page they are in
=> Add correct path to /personaldata for currently active page

src/components/Notifications.js
=> Add span element around notification messages

src/login/styles/_modals.scss
=> Remove span tag from modal header styling

src/components/VerifyIdentity.tsx
=> Add return for rendering help text

src/components/Ladok.tsx, src/login/styles/_Ladok.scss, src/login/styles/_tables.scss
Made settings table status label size relative to document inst of parent (Ove test issue).
Made responsive edits to linked Ladok university.
=> Carina ladok styling

src/login/components/LoginApp/ResetPassword/ResetPasswordLayout.js, src/login/translation/defaultMessages/password.js, src/login/translation/extractedMessages.json, src/login/translation/languages/en.json, src/login/translation/languages/sv.json
=> Remove html <b/> for without extra security heading

src/login/translation/extractedMessages.json, src/login/translation/languages/en.json, src/login/translation/languages/sv.json
=> Fix the swedish help text for frejaeID

src/components/Emails.js, src/components/Mobile.js, src/login/translation/defaultMessages/userProfile.js, src/login/translation/extractedMessages.json, src/login/translation/languages/en.json, src/login/translation/languages/sv.json
=> Fix empty modal header - phone code, email code

src/login/styles/_PersonalData.scss, src/login/styles/_inputs.scss
=> Fix  faulty styling for personal data

src/login/components/Inputs/CustomInput.tsx, src/login/components/LoginApp/Login/UseOtherDevice2.tsx, src/login/components/LoginApp/Login/UsernamePw.tsx, src/login/styles/_Login.scss, src/login/translation/extractedMessages.json
- login on other device button changed to primary 
- add background color for error message to integrate with code
- added email input field invalid- line that  will be red when user gets an error
- removed checkmark icon in password input
=> LOGIN: with other device styling fixes 

src/login/components/LoginApp/Login/UseOtherDevice1.tsx, src/login/components/LoginApp/Login/UseOtherDevice2.tsx, src/login/styles/_Login.scss, src/login/styles/_inputs.scss, src/login/translation/extractedMessages.json
up on timer/code expired
device 1:  enable option to cancel or to retry and added a information message  
device 2:  all content(code inout, device information) to be hidden and showing code expired message
- code expired, device 1
- code expired, device 2
=> LOGIN: get new qr code in device 1 when code expired, hidden content on device 2

package-lock.json, src/login/components/LoginApp/Login/ResponseCodeForm.tsx
add keyboard handling for response code (enable to control with arrow left, right and backspace)
only possible to filled with number
validation input (error message) removed since the input don't allow any other characters
=> LOGIN: edit input field for response code

src/apis/eduidLogin.ts, src/login/components/LoginApp/Login/LoginAbortButton.tsx, src/login/components/LoginApp/Login/UsernamePw.tsx, src/login/redux/slices/loginSlice.ts
Add a button to abort logins, returning the user to the SP. This is useful for example when choosing to change password, getting sent to the IdP and then changing one's mind.
=> add a button to abort logins, calling the new /abort login endpoint

src/components/ChangePasswordForm.tsx, src/components/Emails.tsx, src/components/Orcid.js, src/components/Phones.tsx, src/login/components/LoginApp/Login/UsernamePw.tsx, src/login/components/PersonalData/PersonalDataForm.tsx, src/login/styles/_AccountLinking.scss, src/login/styles/_Login.scss, src/login/styles/_buttons.scss
Added .buttons wrapper where missing, for site-aligned resposive behaviour
Reduced similar wrapper classes
Refactored orcid css and login css
Swapped order of ch pw buttons as to rest of site
(There might be some slight differences in spacing around buttons compared to before but the gain is common code)
=> Frontend buttons wrapper

src/login/app_utils/validation/validateEmail.ts, src/login/components/GroupManagement/EmailForm.js, src/login/components/GroupManagement/Invites/CreateInviteForm.js, src/login/components/Inputs/CustomInput.tsx, src/login/components/Inputs/EmailInput.tsx, src/login/components/Inputs/InputWrapper.tsx, src/login/components/Inputs/PasswordInput.tsx, src/login/components/Inputs/RadioInput.tsx, src/login/components/LoginApp/Login/UsernamePw.tsx, src/login/components/PersonalData/PersonalDataForm.tsx
Refactor CustomInput to a couple of discrete components instead of one trying to work for everything.
Move the "required" part of e-mail and password validation to a submitError in order to have the login button enabled when browsers does auto-complete (Javascript often sees no "value" until the user clicks somewhere). This way, no error message about a missing value is show until after the user has tried to submit the data.
=> refactor custom input fields

src/login/styles/_base.scss, src/login/styles/_links.scss
Vertical content spacing was simplified (all applied to panel), but top padding need to be applied inside to keep notification bar on top, thus reverted.
=> Revert vertical spacing refactor due to notification bar

src/components/GenericError.tsx, src/login/components/LoginApp/LoginApp.tsx, src/login/components/SwamidErrors/Errors.tsx, src/login/styles/_Errors.scss
Aligned to site framework and error-page styling, replaced random buttons with simpler links, removed unnecessary css.
Before:
After:
=> Ct generic error styling

src/login/components/LoginApp/ResetPassword/EmailForm.tsx, src/login/components/LoginApp/ResetPassword/EmailLinkSent.tsx, src/login/components/LoginApp/ResetPassword/GoBackButton.tsx, src/login/components/LoginApp/ResetPassword/ResetPassword.tsx, src/login/components/LoginApp/ResetPassword/ResetPasswordEnterEmail.tsx, src/login/components/LoginApp/ResetPassword/ResetPasswordLayout.tsx, src/login/components/LoginApp/ResetPassword/SetNewPassword.tsx, src/login/styles/_ResetPassword.scss
- Site consistent look and placement of buttons and timer
- Adding/adjusting heading hierarchy across the reset-password steps
- Re-adding lost junk-email copy
- Making goback-button able to use eduid-button link-style
- Replaced empty Lead with strictly visual divider
=> Ct reset password style update

src/components/CodeVerified.tsx, src/reducers/Signup.ts
The backend currently only allows fetching this data once, so in order to still have it after a language switch causes the component to re-render, we have to put it in the redux state instead of in component state.
=> bugfix: have to remember verify-link response in redux state

src/login/app_utils/helperFunctions/navigatorCredential.ts
fixed issue regarding when user cancelling process of adding security key, previous user received an error message "form error"
=> Not send request when cancelling add process for adding security key

src/login/components/LoginApp/ResetPassword/ExtraSecurity.tsx, src/tests/login/LoginResetPasswordExtraSecurity-test.tsx
=> Fixed so that the SMS phone button will not be displayed when user has selected security key

src/login/components/LoginApp/ResetPassword/ExtraSecurity.tsx, src/login/styles/_links.scss, src/tests/login/LoginResetPasswordExtraSecurity-test.tsx
During testing of staging it was found the enter phone code link was not showing properly on "reset password" 
Now rectified and added a test to confirm that the enter code link is showing in the view.
=> Fix enter phone code link not presented

src/components/VerifyIdentity.tsx, src/login/translation/extractedMessages.json
- Add allowZeroExpanded for accordion 
- Svipe -> Foreign Svipe identity
=> fix problem with collapse of accordion onclick after verification of foreign id

src/components/DashboardStart.tsx, src/tests/DashboardStart-test.tsx
1. fix issue: should not render letter proofing progress when the user has verified their identity with swedish id number
2. add tests for dashboard start page
=> should not render letter proofing progress when the user has verified their identity with Swedish id number

src/components/DashboardStart.tsx, src/components/VerifyIdentity.tsx, src/login/styles/_DashboardMain.scss
I have enabled users to perform "letterproofing" on the start page and added logic to expand the accordion on the identity page based on the user's state.
- During the letterproofing process, the user will encounter an accordion on the start page, allowing them to enter the code.
- Accordion expansion is determined by the user's ability to proceed with letterproofing or if phone verification is enabled.
=> Improved "letterproofing" on the start page

src/components/Dashboard/LetterProofing.tsx, src/styles/_DashboardMain.scss, src/styles/_buttons.scss, src/tests/LetterProofing-test.tsx
- Updated description text when the letter is expired.
- Added width for personal number to prevent the button from moving when the show/hide button is clicked 
```
.display-data {
width: 200px;
}
```
- Removed the effect of letters moving slightly when hovering
=> fix minor issues

src/styles/_SignupMain.scss, src/styles/_inputs.scss
I changed the input name from "current-password" to "currentPassword" before, which is why the unique ID styling was not applied.
=> current-password -> currentPassword

src/components/Help.tsx, src/translation/extractedMessages.json
Nested formatted text tags (hope it works!) for language dependent "value" contents in FAQ page (some links, italics, bold).
=> help translatable formatted text and typo

package-lock.json, src/components/Dashboard/Phones.tsx
Issue: Even when the user receives a success response, the error message they previously received is still being presented.
=> Clear notification when the user receives a successful response

src/translation/extractedMessages.json
=> Make translation

src/components/Dashboard/VerifyIdentity.tsx, src/components/Help.tsx, src/components/ResetPassword/EmailLinkSent.tsx, src/components/ResetPassword/SetNewPassword.tsx, src/components/Signup/SignupEnterCode.tsx, src/components/Signup/SignupUserCreated.tsx, src/translation/defaultMessages/signup.tsx, src/translation/extractedMessages.json
Mainly signup related copy/accessibility edits, as specified in separate list
=> Cat copy edits

src/components/Login/ResponseCodeForm.tsx, src/components/Signup/SignupEnterCode.tsx
=> autosubmit function remove in the signup app

src/components/Common/ResponseCodeAbortButton.tsx, src/components/ResetPassword/EmailLinkSent.tsx, src/components/ResetPassword/HandleExtraSecurities.tsx, src/components/ResetPassword/ResetPasswordApp.tsx, src/components/ResetPassword/ResetPasswordMain.tsx, src/components/Signup/SignupEnterCode.tsx, src/machines/ResetPasswordMachine.ts, src/machines/ResetPasswordMachine.typegen.ts, src/tests/login/LoginResetPassword-test.tsx, src/translation/extractedMessages.json
Utilise the email code instead of the email link for reset password flow. remove the resend button and timer, and update the text so that users can cancel the reset password process and retry from the beginning to obtain the code.
---
=> introduce an email code for resetpw

src/slices/PersonalData.ts
Update the handling of postPersonalData to save properties individually, preventing the entire state from being overwritten
=> Fix the issue, overwrite is_verified state

src/components/Common/InputWrapper.tsx, src/components/Common/PasswordInput.tsx, src/components/Dashboard/ChangePasswordCustom.tsx
added autofocus to the custom password inout and ensured that pressing tab moves to repeat password field.
=> add  autofocus for custom password

src/components/Common/NinDisplay.tsx, src/components/Dashboard/VerifyIdentity.tsx, src/styles/_DashboardMain.scss, src/styles/_figure.scss
In mobile mode, when verifying with the Swedish number in the identity tab. the long text "Swedish national Identity number" causes horizontal scrolling and text is duplicated . therefore, I removed the label text and changed "Identity Namer to ID number to prevent the scroll bar from appearing on mobile.
=> Remove duplicated text

src/helperFunctions/cbor.ts
Some browser extensions, e.g. Bitwarden, can't read some data like user.id due to reading the full buffer from a Uint8Array even if it is a typed array view.
See https://github.com/bitwarden/clients/pull/10657 for a patch for the bitwarden browser extension client. 
This patch makes sure to make a copy so that our customers do not get hindered by the misbehaving browser extensions.
See
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/Uint8Array
and
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#parameters
for the technical details
=> patch CBOR for misbehaving extensions

src/apis/eduidSecurity.ts, src/components/Common/Security.tsx, src/components/Dashboard/VerifyIdentity.tsx
There are 3 important elements in the Idp:
- eduID account itself
- MFA / Security Keys that protects the account
- user Identity Verification
The removal of the account is protected by a confirmation modal, but the other 2 can be removed directly by the user without any confirmation. To help avoid the user to remove so critical items by mistake we introduce a "confirm modal" also for Identity Verification and Security Keys.
However we consider that those 2 functions has been protected by the "security zone"/re-auth which has its own modal. To reduce the amount of clicks the user has to do to achieve the removal, we consider to show only 1 modal:
- either the confirmation modal, if the user does not need to re-auth
- or the re-auth modal, when we know the user has to re-auth. This will …
=> Add "confirm remove modal" when deleting Identity Verfication or Security Key

src/components/Login/SecurityKey.tsx, src/translation/extractedMessages.json
=> fix help text to the security key button in the MFA page

src/components/Common/PersonalDataForm.tsx
users who verified with eidas get error message when they try to update names. updating names is now only available for users verified with swedish methods.
=> Update name is only available for nin verified

src/components/Common/Security.tsx
add state isRegisteringAuthenticator to disable "security key" or "device" buttons when registering a new security key
=> Add state isRegisteringAuthenticator and disable add "security key"/"device" buttons when isRegisteringAuthenticator state in true

src/components/Common/ConfirmModal.tsx, src/components/Common/CopyToClipboardButton.tsx, src/components/Common/PasswordInput.tsx, src/components/Common/Security.tsx, src/components/Dashboard/AccountId.tsx, src/components/Dashboard/ChangePasswordSuggested.tsx, src/components/Dashboard/VerifyIdentity.tsx, src/components/IndexMain.tsx, src/components/ScrollToTop.tsx, src/styles/_ResetPassword.scss, src/styles/_buttons.scss, src/styles/_label.scss, src/translation/extractedMessages.json
- copy icon before field to be copied inst of after
- translatable hover title on X- icon where identity is removed
- added reusable scrolltotop component, included in indexmain at navigation.
- added optional maintext paragraf in confirm modal with text to explain key naming
- reused border site-variabel for mfa-toggle
=> Cat post obs fixes

src/components/Common/MultiFactorAuthentication.tsx
Fix the issue when multiple modals open when removing a security key and there are multiple security keys
=> Move the modal outside map function to prevent opening multiple modals

src/components/Common/ConfirmModal.tsx, src/components/Common/EduIDTextInput.tsx, src/components/Common/InputWrapper.tsx, src/components/Common/PersonalDataForm.tsx, src/components/Dashboard/AccountId.tsx, src/components/Dashboard/Ladok.tsx, src/components/Login/UseOtherDevice2.tsx, src/components/Login/UsernamePw.tsx, src/styles/_DashboardMain.scss, src/styles/_SignupMain.scss, src/styles/_forms.scss, src/styles/_label.scss
- Set the input height to prevent changes when an error occurs under the input
- Fix a few web accessibility issues. Fields must be inside a form, and labels should be associated with the inputs
- Remove fieldsets outside the <Field />
=> Set the height for the signup input fields and fix web accessibility issues

src/components/ResetPassword/EmailLinkSent.tsx, src/components/ResetPassword/ResetPasswordEnterEmail.tsx, src/translation/extractedMessages.json
Adding sender email (no-reply@eduid.se) to reset password flow, with user email user-entered and pre-entered, to ease retrieval of e-mailed code.
=> Cat sender email reset pw

src/components/Common/SecurityKey.tsx
The disabled prop prevents the button focus ref
=> Fix: Button ref not working, even though using the same component

src/components/ScrollToTop.tsx, src/tests/AccountLinking-test.tsx, src/tests/AdvancedSettings-test.tsx, src/tests/BankID-test.tsx, src/tests/DashboardMain-test.tsx, src/tests/DashboardStart-test.tsx, src/tests/DeleteAccount-test.tsx, src/tests/Eidas-test.tsx, src/tests/Emails-test.tsx, src/tests/FrejaeID-test.tsx, src/tests/LetterProofing-test.tsx, src/tests/Security-test.tsx, src/tests/VerifyIdentity-test.tsx, src/tests/login/LoginMain-test.tsx, src/tests/login/LoginResetPassword-test.tsx
Cleanup some of the errors and warning that are output during tests
* replace only use of window.scrollTo with window.scroll to unify usage
* mock window.scroll in more tests
* as per warnings use act from react and not from react-dom/test-utils
=> Cleanup some errrors and warnings

src/eduid-init-app.ts, src/notify-middleware.ts
Limit the use of redux-logger middleware to development
=> Limit logging to development environment

src/components/Common/PasswordInput.tsx
Add password input focus so that when the email is already filled in, the user is able to enter their password easily.
=> Add password input focus

src/components/Common/PasswordInput.tsx, src/components/Dashboard/ChangePasswordSuggested.tsx, src/styles/_ResetPassword.scss, src/styles/_buttons.scss, src/styles/_inputs.scss
Reused css,
repositioned copy/copied after input 
and show/hide before input, in relative container.
Test for login pw, change/forgotten pw and eppn at start.
=> show-hide and copy-copied repositioned

src/apis/eduidLogin.ts, src/components/Common/SecurityKey.tsx, src/components/Login/Login.tsx, src/components/Login/MultiFactorAuth.tsx
Add this_device (known device info) to login mfa endpoint requests.
=> minimal patch to make login work with security key first

src/styles/_darkmode.scss, src/styles/_landingPage.scss
Making text links more legible in dark mode,
counter responsive overlap on landing how to section as seen in Brave browser screenshot.
=> Cat link weight

src/styles/_Header.scss, src/styles/_buttons.scss
Visual fixes:
- left focus border on submeny was cut off
- refresh button (icon + text) was silly responsive, now keeping together to the left, with line-height for responsive legibility.
=> Cat submenu fokus fix

src/apis/eduidSecurity.ts
This PR wires up the GET end point of `authn-status` of the security service for further uses for showing the user why certain security actions are needed
=> Add api end point for checking authn status

src/components/Common/SecurityKey.tsx, src/components/Login/MultiFactorAuth.tsx, src/components/ResetPassword/HandleExtraSecurities.tsx, src/slices/Login.ts
Refactor SecurityKey
* Moves logic from sub-component SecurityKeyActive to whatever uses SecurityKey.
* SecurityKey component handles authentication by `navigator.credentials`
* setup and further logic are used via callbacks
This fixes the edge case of not having an active SSO session and having "remember me" set and cancelling first authentication, further retries are not possible until reload as the logic missed sending device information on subsequent authentication requests.
=> Refactor SecurityKey

src/styles/_Header.scss
=> fix, when clicking the menu on mobile, the menu text and arrow up/down slightly shift
